### ISSUE TITLE
[ASEditableTextNode] First line is eating emojis

### ISSUE THREAD

**Issue by logicsb** [facebookarchive/AsyncDisplayKit#1154]
Hi, the ASEditableTextNode component is eating emojis in the first line when using custom font styles

```
// style of the attributedText
class func feedPostCellContent () -> [String:AnyObject] { // Content
        var style = [NSFontAttributeName: UIFont(name:"MyriadPro-Light", size:14.0)!, NSForegroundColorAttributeName: UIColor.blackColor()]
        let paragraph = NSMutableParagraphStyle()
        paragraph.lineSpacing = 8
        style[NSParagraphStyleAttributeName] = paragraph

        return style
 }
```

Screenshot:
![screen shot 2016-01-30 at 6 24 50 pm](https://cloud.githubusercontent.com/assets/1790860/12698255/4bc11b40-c77f-11e5-8a0a-0eed93abb7b1.png)

**Comment by appleguy** [comment]
Could you try this out with UITextView?  That is what this class uses under the hood, and it may well have the same issue. Feel free to check out the implementation, as it is less magical than most other components in the framework… So if there is a bug in the editable node implementation, you could probably help us locate what might be causing it. Unfortunately though, I bet this is just an Apple issue.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#120
