### ISSUE TITLE
[ASTableView, ASCollectionView] Return Incorrect Counts If Queried During nodeForItem/Row

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#1159]
I've added failing test cases for this in [AHTestDataSourceCountsDuringNodeForItem](https://github.com/Adlai-Holler/AsyncDisplayKit/tree/AHTestDataSourceCountsDuringNodeForItem) specifically [7c90ef](https://github.com/Adlai-Holler/AsyncDisplayKit/commit/7c90eff4ca719118622bb891587b2f90e79d7ee5).

I'm not saying reading these values during nodeForRow is great practice, or that this issue is high-priority, but it's a divergence I noticed from UIKit's classes.

**Comment by hannahmbanana** [comment]
@Adlai-Holler - was this fixed by the new table node / collection node API?

**Comment by Adlai-Holler** [comment]
@hannahmbanana Unfortunately not. The counts are currently updated just _after_ calling `nodeBlockForItem:` and friends =/.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#121
