### ISSUE TITLE
[ASTextNode] Setting hyphenationFactor option sometimes truncates text

### ISSUE THREAD

**Issue by nvh** [facebookarchive/AsyncDisplayKit#1284]
See the example project here: https://github.com/nvh/ASTextNodeTest/tree/hyphenation-factor-bug

When no hyphenationFactor is specified the text is rendered correctly:

<img src="https://cloud.githubusercontent.com/assets/248861/13378873/f9e253d2-de14-11e5-91fd-85b9dba13668.png" width="375">

But when I specify a `hyphenationFactor` of 0.5, the last word is cut off:

<img src="https://cloud.githubusercontent.com/assets/248861/13378876/0b836356-de15-11e5-8470-a2d32a8a80aa.png" width="375">

Sorry for the dutch in the examples, it was the easiest way to recreate the problem. Although the dictionary used by CoreText for hyphenation is based on the language set by iOS it doesn't matter for this example if the simulators language is set to English or Dutch. However I have seen an example (but haven't been able to reproduce in a controlled setting) where the language setting _did_ matter for the occurrence of this bug.

**Comment by appleguy** [comment]
@rcancro have you encountered any issues like this in your work, or do you have a test harness that could help isolate where in the stack it's occurring?

@nvh thanks a lot, I'm looking forward to getting the text stuff dialed in for good as soon as we can.  There are now a couple full time folks working on ASDK, and though this will not be their top priority for a few weeks, a fix should be possible before the end of March.

**Comment by nvh** [comment]
@appleguy Thanks! Was hoping to get this fixed earlier, because we're shipping next week, but understand that the team has other priorities.

**Comment by rcancro** [comment]
I was seeing similar behavior before I took the word kerner out of ASTextNode. @nvh are you up to date with master? If not can you update and give it a try?

**Comment by nvh** [comment]
@rcancro This is build against 3671f5cbc5d5a0265a03389c2d88e04ac5c275d5, so up to date with master as of yesterday

**Comment by appleguy** [comment]
@nvh a key change has been made and that may have fixed this (@rcancro's one line diff). Could you please try the latest master, and report back here with the results? If you don't have an opportunity to check, then no worries, I will circle back when I have time. Feel free to close the task if it is working correctly. The fix is speculative, in that it was not designed specifically for this issue, but does fix other issues related to centered text.

**Comment by nvh** [comment]
@appleguy unfortunately the speculative doesn't fix the problems in either the test project or the original case :disappointed:
What are the issues that are fixed by this commit? We're shipping tomorrow, and want to decide if t's worth it to ship with the latest master or err on the safe side and take the latest release.

**Comment by tacovollmer** [comment]
Hi @appleguy is there any news on this issue? (I've taken over responsibility from @nvh for our app)

**Comment by tacovollmer** [comment]
This issue is still present in `1.9.90` @appleguy

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#125
