### ISSUE TITLE
[ASDisplayNode] After setting borderColor in init(), changing it on tintColorDidChange does nothing

### ISSUE THREAD

**Issue by jellenbogen** [facebookarchive/AsyncDisplayKit#1315]
Hi Guys,

I'm observing what I think to be strange behavior when trying to update the border color of my node on tintColorDidChange.

What's happening is I initially set the nodes border color to tintColor in the init() method, then when tint color changes I'm updating the node's borderColor in tintColorDidChange, however I'm not seeing any change in border color. I've changed other color properties in tintColorDidChange and they worked. 

I've included simplified test files to show what I'm doing. Also a note in the examples, if I don't set the the borderColor = tintColor.CGColor in the init() method, and only set in in the container node, then I do see the borderColor show as red.

[BorderColorTest.zip](https://github.com/facebook/AsyncDisplayKit/files/157765/BorderColorTest.zip)

**Comment by garrettmoon** [comment]
Hey @jellenbogen we're trying to clear out some of our old issues, sorry this never got a reply. Would you mind seeing if this is still an issue and if it is uploading a complete project? It'd be an amazing help.
