### ISSUE TITLE
[ASCellNode] UIViewController-backed Cell Nodes May Not Receive viewWillAppear:

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#1541]
I have an ASPagerNode with view controller-backed cell nodes. The first page does not get `viewWillAppear:` on first appear.

When I do get it (for other nodes, or after scrolling away and coming back), it comes via two separate backtraces:
- directly from `[UICollectionView layoutSubviews]`, I suspect this is when the collection view moves an already-configured cell into itself.
- from `[ASRangeController configureContentView:forCellNode:]` in `[contentView addSubview:node.view]` where the UICollectionViewCell is already in a window.

When the range controller configures the first page for the initial appear, the cell is not in a window, so `[contentView addSubview:]` doesn't trigger a `viewWillAppear:`.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#128
