### ISSUE TITLE
[ASCollectionNode / ASTableNode] Method to Wait for Initial Nodes to Be Loaded

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#1584]
`waitUntilAllUpdatesAreCommitted` is great! Could we go even further and make a variant that waits until the initial nodes are all measured and inserted as well?

I've got a pager node with 3 tabs, and I'd like to push a VC already jumped to the third tab, but I can't. I add `waitUntilAllUpdatedAreCommitted` in `viewWillAppear` and it has no effect, because `_editingTransactionQueue` is empty but numberOfSections is 0. `viewDidLayoutSubviews` is no help either because my view controller's view is a container that holds the pager inside it. Currently my best option is to async out of `viewWillAppear:` and hope that by then the nodes are ready, else to poll repeatedly and jump as soon as I see `numberOfItemsInSection:` is correct but these aren't ideal.

@nguyenhuy Any advice?

**Comment by maicki** [comment]
@Adlai-Holler Agree we should have that ability and I'm actually working on something that could provide this kind of functionality, but for a workaround what happens in you case if you call `reloadDataImmediately` in `viewWillAppear:` and than jump to the third page?

**Comment by Adlai-Holler** [comment]
That definitely works. In fact I'm thinking more and more that one easy way to implement this would be to always vend 0 items during the first data load, and then use an edit operation to insert all the initial content, and then we can simply wait until those operations are finished as needed. I've done that client-side and it works, and maybe we could move it into ASTableView/ASCollectionView.

**Comment by maicki** [comment]
Sounds an interesting idea.

Just quick follow up you could also do `reloadDataWithCompletion:` in `viewWillAppear:` and in the completion block scroll to the index.

**Comment by appleguy** [comment]
@Adlai-Holler: are you implying that adding a call to wait for all operations to be committed does not actually work for the initial data load? 

This is similar to issue #1642.

**Comment by Adlai-Holler** [comment]
@appleguy Yes, unfortunately. It's possible this was fixed in the interim but if so I didn't hear about it =/

**Comment by hannahmbanana** [comment]
@Adlai-Holler - can this be closed?

**Comment by Adlai-Holler** [comment]
Unfortunately not, but it's a much less critical issue now. You can force the initial content load by doing:

```
[collectionNode numberOfSections];
// or
[collectionNode.view layoutIfNeeded];
// then
[collectionNode waitUntilAllUpdatesAreCommitted];
```

There are a number of reasonably easy ways to fix this, including:
- In `ASCollectionNode`, call `[self reloadDataInitiallyIfNeeded]` inside of `waitUntilAllUpdatesAreCommitted`.
- In `ASDataController` do basically the same thing.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#129
