### ISSUE TITLE
[ASPagerNode] Convenient way to initialize an ASPagerNode's initial cell

### ISSUE THREAD

**Issue by plm75** [facebookarchive/AsyncDisplayKit#1642]
Currently, the only way to set an ASPagerNode's initial cell is to call `scrollToItemAtIndex`.  However, this method can only be called after the ASPagerNode's data has been fully loaded and the view laid out.

One workaround consists in wrapping the call to `scrollToItemAtIndex` inside an `async_after`, another is to call it after `reloadDataImmediately`.

The first workaround is just an ugly hack, the second is too expensive.  A better and more convenient way to set an ASPagerNode's initial cell would be nice.

cc @hannahmbanana

**Comment by maicki** [comment]
@plm75 Agree dispatch_after is a hack and I would recommend try to not using it. Just fyi: you can also use `scrollToItemAtIndex:` in `reloadDataWithCompletion:`, this would not be that be expensive as `reloadDataImmediately`.

**Comment by Jauzee** [comment]
@plm75 Have you got a solution for this issue?

Currently I'm use `scrollToPageAtIndex` method in `viewDidAppear` and it looks very ugly, I'm thinking about make some loader & fade in, but maybe it's not best idea in this case.

**Comment by appleguy** [comment]
A much, much better option is to manually calculate the content offset.  You can use setContentOffset: right away.  This would probably require manually setting the contentSize to at least that amount, though; it will then be reset as the collection loads its content for the pager.

A tricker but even better solution would be to initially add just the page you want to show to the datasource (as the /only/ page), so it shows up quickly, but then insert all the other pages and scroll to the correct page.  Done carefully, this could be really slick.

Overall, make sure you try to avoid exposing many hundred or thousands of items to the data source all at once.  If you can limit that to under a hundred, it is usually acceptable to use -waitUntilAllTransactionsAreCommitted in viewWillAppear: and then you can scroll to the correct page immediately.

**Comment by Jauzee** [comment]
@appleguy thank you for detailed answer, I've been used this for a while.

Any updates in ASDK 2.0?

**Comment by garrettmoon** [comment]
Since there seem to be several work arounds for this, I'm marking it as a P3

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#133
