### ISSUE TITLE
ASViewController does not resize when the size class changes from compact to regular.

### ISSUE THREAD

**Issue by KristopherGBaker** [facebookarchive/AsyncDisplayKit#1959]
AsyncDisplayKit Version: 1.9.81 / master

I'm experiencing an issue with size class changes that looks similar to #1905, but occurs on iOS 9.  The issue does not occur with release 1.9.80, but does show up in both 1.9.81 and master.  

The app is composed of a custom tab bar container view controller (not based on UITabBarController) as the root view controller, with each tab a subclass of ASViewController.  The nodes for the ASViewController are subclasses of ASCollectionNode.

I first noticed this issue on an iPhone 6s Plus where, if a tab's view controller is initially loaded in landscape, then rotation between landscape and portrait appears to work fine.  But, if a tab's view controller is initially loaded in portrait, then rotating to landscape shows the issue (size class changes from compact to regular).  The view backing the ASViewController never seems to get resized correctly for landscape.  The examples in #1905 are similar to what I'm seeing.  Here's a couple of screenshots as well.  I initially thought this was a rotation problem, but the issue does not occur on an iPhone 6s, which leads me to believe it's related to size class changes.

As I commented below, I see a similar issue when switching between different split view sizes on the iPad Pro.

Portrait: ![Portrait](https://cloud.githubusercontent.com/assets/140792/17007112/46d26a02-4ea3-11e6-9898-9a712552ed3a.png)

Landscape after rotating from portrait (view controller initially loaded in portrait, scrollbar shown to show the right side of the view): ![Landscape after rotating from portrait](https://cloud.githubusercontent.com/assets/140792/17007125/5aef211a-4ea3-11e6-8c0d-f088f3754dee.png)

Landscape if view controller is initially loaded in landscape (this is what I expect to see in all cases instead of the above screenshot) ![landscape-good](https://cloud.githubusercontent.com/assets/140792/17007169/ad5b02de-4ea3-11e6-9280-d236f49b6ac6.png)

**Comment by KristopherGBaker** [comment]
Another thing I just noticed.  I've only seen the rotation problem on the iPhone 6s Plus so far (both real device and simulator).  iPhone 6s handles rotation correctly.  Changing between split view sizes on the iPad Pro also shows a similar issue (no rotation involved, but it shows the same issue of the ASViewController's view not getting resized).  Could it be something related to size class changes / trait collection changes when the size class changes from compact to regular?

**Comment by maicki** [comment]
@KristopherGBaker Hey Kristopher, can you please try out ASDK master if it's still happening? Thanks! - Michael

**Comment by KristopherGBaker** [comment]
@maicki Hi Michael, I just tried master and it is still happening.  If I have time later, I'll see if I can reproduce it in an example project.

**Comment by KristopherGBaker** [comment]
I replaced the custom tab bar controller with UITabBarcontroller and it works as expected with master.  Perhaps there is something missing in the custom tab bar controller (although this problem wasn't present in 1.9.80) - will see if I can fix the tab bar controller.

**Comment by KristopherGBaker** [comment]
@maicki Hey Michael, I've narrowed down where the issue is happening a bit more.

After fixing a missing call to super.viewWillTransitionToSize in one of my container view controllers, I have it working as expected if I update viewWillTransitionToSize in ASViewController.mm to set the node's size as below.  I don't know if this is the right way to go about it, and I can just do the same thing in my view controller instead of ASViewController, but this wasn't necessary with 1.9.80.

One other thing about all of this - the view that the ASViewController node's view ends up as a subview of (the container VC for the ASViewController), has auto layout constraints (and translatesAutoresizingMaskIntoConstraints = false/NO).

```objc
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator
{
  [super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
  
  ASEnvironmentTraitCollection environmentTraitCollection = [self environmentTraitCollectionForWindowSize:size];
  [self progagateNewEnvironmentTraitCollection:environmentTraitCollection];
  self.node.bounds = {
    self.node.bounds.origin.x,
    self.node.bounds.origin.y,
    size.width,
    size.height
  };
}

**Comment by garrettmoon** [comment]
I'm going to close this out as it's community debugging and hasn't been commented on for quite some time.
