### ISSUE TITLE
[ASNetworkImageNode] Can't update URL/image after setting animated GIF

### ISSUE THREAD

**Issue by abaerlocher** [facebookarchive/AsyncDisplayKit#1991]
We're using ASNetworkImageNode to load/display image URLs in our app. The views are recycled as new images are displayed. Occasionally, an animated GIF is displayed. Once an animated GIF URL has been set, however, it's not cleared/removed when another image URL is set. It continues to display the animated GIF.

This is easy to reproduce using the 'AnimatedGIF' sample project (included in AsyncDisplayKit v1.9.81). After running the animated GIF for a few seconds, set the image node URL to a JPEG, for example. The animated GIF will flash but continue to display. I've tried to work around this by resetting the URL and calling clearFetchedData() (this caused a deadlock). For now, the only option is to remove the image node and instantiate a new one each time.

**Comment by hannahmbanana** [comment]
@garrettmoon: is this intended behavior?

**Comment by garrettmoon** [comment]
No, definitely not!

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#135
