### ISSUE TITLE
[ASCellNode] Provide setHighlighted/setSelected methods to allow the change of opaque node's background color before row selection

### ISSUE THREAD

**Issue by Arko4576** [facebookarchive/AsyncDisplayKit#2037]
Currently `ASCellNodes` will highlight their subnodes as long as they are not opaque but if they are opaque the nodes background color will not be changed to match. Having opaque views gives scroll performance gains that would be nice capitalize on while keeping the user interaction.

![example](https://cloud.githubusercontent.com/assets/8193100/17424070/6138f5a4-5a8e-11e6-8467-23f91905f2f3.png)

This is how a highlighted `ASCellNode` appears with an opaque/backgroundcolor set subnode on highlight. `UITableViews` will change the background color of opaque subviews automatically but also provide other methods for highlighting views. 

One of these methods is `setHighlighted` and `setSelected` methods which can be overridden by `UITableViewCell` subclasses and are called right before the cell is highlighted. I've tried implementing a basic example of this but the problem that arises is that the background colors of the nodes you change don't get updated quick enough to be in sync with the cell highlight.

I would guess that the hardest part of implementing this would be `ASTextNodes` as their rendering may not allow for quick updates to the background color.

I've been looking into this for awhile to no avail but though it might be something to keep on radar for future versions.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#137
