### ISSUE TITLE
[ASNetworkImageNode displayWillStart] sometimes will blocking main thread on tableViewcell

### ISSUE THREAD

**Issue by 12207480** [facebookarchive/AsyncDisplayKit#2056]
[ASNetworkImageNode displayWillStart] sometimes will blocking main thread on tableViewcell.<br>
[ASNetworkImageNode displayWillStart]  is called on a different thread / main ,but on main thread will blocking UI.cause serious caton.
![image](https://cloud.githubusercontent.com/assets/6346030/17584058/f991646e-5fe6-11e6-92cf-161f12c495ba.png)

**Comment by 12207480** [comment]
![image](https://cloud.githubusercontent.com/assets/6346030/17584189/cb25fc38-5fe7-11e6-8d3c-7fdfce3fa2cb.png)

**Comment by 12207480** [comment]
![image](https://cloud.githubusercontent.com/assets/6346030/17584220/f1369662-5fe7-11e6-8541-cc2aa652ed37.png)

**Comment by 12207480** [comment]
the image size 1000x324;

**Comment by hannahmbanana** [comment]
@12207480: Are you using a `UITableViewCell` or an `ASCellNode`? 

do you set either `.displaysAsynchronously = NO` or 
`.neverShowPlaceholders = YES` or 
`-recursivelyEnsureDisplaySynchronously:YES`?

It looks like what is happening is that the `ASNetworkImageNode` has not finished rendering by the time it is about to be shown onscreen and that it has been configured to do so synchronously (like UIKit behavior).

**Comment by 12207480** [comment]
using  ASCellNode ，don't set others

**Comment by 12207480** [comment]
@hannahmbanana  
<br>[LovePlayNews.zip](https://github.com/facebook/AsyncDisplayKit/files/417518/LovePlayNews.zip)
<br>this is demo . on home (news) , scroll very fast will casue blocking UI。run in iphone not simulator。
<br>you can look  LPNewsListController and LPNewsImageCellNode or LPNewsCellNode  (ASNetworkImageNode *imageNode;).

**Comment by hannahmbanana** [comment]
@12207480: Would it be possible to include the full profile (.trace file)? 

I peaked at your app. It's very cool! You might consider adding placeholders to your images. It's really easy using these steps [placeholders](http://asyncdisplaykit.org/docs/placeholder-fade-duration.html) and UIImage+ASConveniences.[hm] convenience methods.

**Comment by 12207480** [comment]
@hannahmbanana 

Thank you，I will use  placeholder。

this is  trace file 。

![image](https://cloud.githubusercontent.com/assets/6346030/17686052/ca65ca00-639b-11e6-971f-31a6cdd69ed1.png)

[lovePlayNews.trace.zip](https://github.com/facebook/AsyncDisplayKit/files/419367/lovePlayNews.trace.zip)

**Comment by 12207480** [comment]
@hannahmbanana 
hello, I want to know the problem solved ?

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#138
