### ISSUE TITLE
[ASDisplayNode] subclass layout and sizing

### ISSUE THREAD

**Issue by zdenektopic** [facebookarchive/AsyncDisplayKit#2058]
Hello,
I have issue understanding how does ASDisplayNode subclass sizes itself. I have a simple code looking like this.

```
public enum LogoType {

    case Red
    case White

    var image: UIImage {
        return UIImage(named: "s-" + (self == .Red ? "red" : "white"))!
    }

}

public class OmniboxBarNode: ASDisplayNode {

    public var logoType: LogoType = .White {
        didSet {
            sNode.image = logoType.image
        }
    }

    private let sNode = ASImageNode()
    private let omniboxFieldNode = ASEditableTextNode()

    override public init() {
        super.init()
        usesImplicitHierarchyManagement = true

        setup()
    }

    private func setup() {
        backgroundColor = .blueColor()

        sNode.image = logoType.image
        omniboxFieldNode.backgroundColor = .redColor()
    }

    public override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
        let height: CGFloat = 40

        let stack = ASStackLayoutSpec()
        stack.direction = .Horizontal
        stack.justifyContent = .Center

        omniboxFieldNode.flexGrow = true

        stack.setChildren([sNode, omniboxFieldNode])
        return stack
    }

    public override func calculateSizeThatFits(constrainedSize: CGSize) -> CGSize {
        return CGSize(width: constrainedSize.width, height: min(40, constrainedSize.height))
    }

}
```

It is completely OK for me to OmniboxBarNode to size itself, it knows whats best height for the bar and knows it wants to be in full width of superview/node. So code like this would work:
`let size = CGSize(width: constrainedSize.max.width, height: max(constrainedSize.min.height, min(height, constrainedSize.max.height)))`
But I have no idea where to put it since i did `implement calculateSizeThatFits(constrainedSize: CGSize) -> CGSize` and `layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec`

However I am still getting assert:

> **\* Assertion failure in -[ASDKTest.OmniboxBarNode calculateLayoutThatFits:], /Users/zdenektopic/Projects/Personal/ASDKTest/Pods/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:1945
> 2016-08-11 14:28:56.919 ASDKTest[1665:566822] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Subclass ASDKTest.OmniboxBarNode must at least provide a layoutSpecBlock or override at most one of the three layout methods: calculateLayoutThatFits, layoutSpecThatFits or calculateSizeThatFits'
> ---

**Comment by zdenektopic** [comment]
So I have figured I need to implement only one method so I did this:
```
public class OmniboxBarNode: ASDisplayNode {
    
    public var logoType: SLogoType = .White {
        didSet {
            sNode.image = logoType.image
        }
    }
    
    private let sNode = ASImageNode()
    private let omniboxFieldNode = ASEditableTextNode()
    
    override public init() {
        super.init()
        usesImplicitHierarchyManagement = true
        
        setup()
    }
    
    private func setup() {
        backgroundColor = .blueColor()
        
        sNode.image = logoType.image
        omniboxFieldNode.backgroundColor = .redColor()
    }
    
    public override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
        let height = max(constrainedSize.min.height, min(40, constrainedSize.max.height))
        let size = CGSize(width: constrainedSize.max.width, height: height)
        sizeRange = ASRelativeSizeRangeMakeWithExactCGSize(size)
        
        let stack = ASStackLayoutSpec()
        stack.direction = .Horizontal
        stack.justifyContent = .Center
        
        omniboxFieldNode.flexGrow = true
        
        stack.setChildren([sNode, omniboxFieldNode])
        return stack
    }
    
//    public override func calculateSizeThatFits(constrainedSize: CGSize) -> CGSize {
//        return CGSize(width: constrainedSize.width, height: min(40, constrainedSize.height))
//    }
    
}
```

However it seems like `sizeRange` doesn't work and I cannot figure out why. Same of `preferredFrameSize`.

**Comment by zdenektopic** [comment]
Attaching project.
[ASDKTest.zip](https://github.com/facebook/AsyncDisplayKit/files/413479/ASDKTest.zip)

**Comment by hannahmbanana** [comment]
@zdenektopic: Certain <ASLayoutable> properties will only apply when the layoutable is a child of a *stack* spec (the child is called an ASStackLayoutable), while other properties only apply when the layoutable is a child of a *static* spec (the child is called an ASStaticLayoutable). 

- `.preferredFrameSize` is an `ASStackLayoutable` property that only works when it is set on the child of a stack layout spec. 
- `.sizeRange` is an `ASStaticLayoutable` property that only works when it is set on the child of a static layout spec. 

http://asyncdisplaykit.org/docs/layout-api-debugging.html

**Comment by hannahmbanana** [comment]
- For your `.sizeRange` property to apply, you will need to wrap the `stack` variable in an `ASStaticLayoutSpec`. 
- `.preferredFrameSize` must be set on a node or layoutSpec for it to take affect. 

It would help to have a picture of the UI you are trying to achieve, but I'm guessing that you want something like this:

```
    public override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {
    
        // set flexGrow on textNode to allow it to stretch to fill space
        omniboxFieldNode.flexGrow = true
      
        // horizontal stack
        let stack = ASStackLayoutSpec(direction: .Horizontal,
                                      spacing: 8,
                                      justifyContent: .SpaceAround,
                                      alignItems: .Center,
                                      children: [sNode, omniboxFieldNode])
      
        let height = max(constrainedSize.min.height, min(40, constrainedSize.max.height))
        let size = CGSize(width: constrainedSize.max.width, height: height)
        stack.sizeRange = ASRelativeSizeRangeMakeWithExactCGSize(size)
      
        // wrap stack in staticSpec to apply .sizeRange
        let staticSpec = ASStaticLayoutSpec(children: [stack])
      
        return staticSpec
    }
```

Let me know if this isn't what you want and I can help make changes.

**Comment by zdenektopic** [comment]
I see, thanks.

Also I have question regarding other node properties like `backgroundColor`, should I set those too in `layoutSpecThatFits(_:)` instead of my current `setup()` method?

**Comment by hannahmbanana** [comment]
@zdenektopic: It depends. If the property is one of `ASDisplayNode`'s bridged `UIView` / `CALayer` properties - e.g. `backgroundColor` or `alpha` and they only need to be set **once**, you can set these directly on the node in `init`. 

You can set these node properties in`layoutSpecThatFits:`, but this method will get called many times, so it is less performant to do it in the `layoutSpecThatFits:` method if you do not need to change these properties. 

This is a good read on where layout code should go in node subclasses: http://asyncdisplaykit.org/docs/subclassing.html

**Comment by garrettmoon** [comment]
Going to close this out since it's community debugging and hasn't been commented on in a while.
