### ISSUE TITLE
ASTextNode underestimated descender/ascender

### ISSUE THREAD

**Issue by nlutsenko** [facebookarchive/AsyncDisplayKit#2061]
Looks like `ASTextNode` while performing layout and drawing can potentially cut-off a single pixel (half a point) in the descenders of some fonts.
From my investigation - the underestimation happens inside TextKit NSLayoutManager, where it returns the `boundingRectForGlyphRange:inTextContainer:` and `usedRectForTextContainer:` that is slightly off.

This was reported and attempted to be fixed in #637

Repro:
- Use `Kittens` from the `examples` folder
- Change all the placeholder texts to `@[ @"gggggg" ]`
- Change the font to `HelveticaNeue` with `30.0` point size
- Observe the screenshot:
  ![simulator screen shot aug 11 2016 12 50 05 pm](https://cloud.githubusercontent.com/assets/606991/17602597/2e14293a-5fc2-11e6-8cfd-39e868eb0cd6.png)

Whilst the proper one should be:
![simulator screen shot aug 11 2016 12 50 21 pm](https://cloud.githubusercontent.com/assets/606991/17602604/34bf9f9e-5fc2-11e6-9318-0901cacadff9.png)

**Comment by nlutsenko** [comment]
What we ended up doing in Instant Articles is literally increasing the bounding box for the text node by `3.0` for ascender and `0.5` for descender, but I have a feeling that this is not the correct approach.

After looking around for similar issues - looks like not a whole lot of people encountered this, but there are absolutely reports about `boundingRectForGlyphRange:inTextContainer:` and `usedRectForTextContainer:` returning different sizes compared to CoreText.

Would love to hear your thoughts guys about the approach that we should take here to fix it once and for all for everyone.

**Comment by ocrickard** [comment]
I tested this with CKTextComponent/LabelComponent, and I'm not seeing the same issues. There must be a difference in the sizing or in the origin positioning of the layout manager.

Here's an example of 30pt HelveticaNeue in the ComponentKit demo project:

![simulator screen shot aug 11 2016 4 47 31 pm](https://cloud.githubusercontent.com/assets/857665/17604374/882f6fb2-5fe3-11e6-817a-b8b5ab7558f8.png)

**Comment by nlutsenko** [comment]
@ocrickard, here you go:
A good repro of text being cut off from ComponentKit.
![simulator screen shot aug 11 2016 3 22 20 pm](https://cloud.githubusercontent.com/assets/606991/17606975/71ea54da-5fd7-11e6-80a4-c4b3372f0dea.png)

**Comment by nlutsenko** [comment]
^ The only change in above is replacing all the quotes with `gggg` and replacing the font on the frosted component with `HelveticaNeue`.

**Comment by nlutsenko** [comment]
![simulator screen shot aug 11 2016 4 01 41 pm](https://cloud.githubusercontent.com/assets/606991/17607801/ea7ef82e-5fdc-11e6-8689-68a8d41c0cef.png)
Here is another one, just for reference - this is using `HelveticaNeue-Italic`

**Comment by hannahmbanana** [comment]
@garrettmoon: this appears similar to the other issue you were investigating?

**Comment by garrettmoon** [comment]
Similar but slightly different, in the italicized case, UILable will clip too. In the original case here (helveticaneue, 30pt, ggggg), UILabel *doesn't* clip it but ASTextNode does :/

**Comment by ocrickard** [comment]
Uggh, that's too bad. We're just using vanilla TextKit to determine the size of the glyphs I believe? We've had the same troubles internally with CoreText for years.

**Comment by nlutsenko** [comment]
Yup, looks like it's an issue with TextKit internals. What do you guys think should be the best way to fix this?

**Comment by ocrickard** [comment]
Looks to me like UILabel is still rendered and sized using NSStringDrawing, so I'm not surprised at the difference. I'd compare to UITextView.

**Comment by garrettmoon** [comment]
Hmm, good point, I'll try that out real quick

**Comment by garrettmoon** [comment]
@ocrickard UITextView also appears to work correctly… hmmm

**Comment by ocrickard** [comment]
As for how to fix:

1. We have to ensure that we're properly handling every origin that TextKit returns. If we're not respecting the origins they give us, then we can end up offsetting a small amount and cause clipping.

2. I'm open to consider adding padding to the text container. I believe this is what UITextView does :(

**Comment by garrettmoon** [comment]
@ocrickard there's a PR up for adding padding: #2062

**Comment by ocrickard** [comment]
@nlutsenko what OS version are you testing on for ComponentKit? I can't repro with the same strings and font sizes for the descender clipping.  The italic clipping issue is likely a separate issue.

**Comment by nlutsenko** [comment]
iPhone 6s simulator running from inside Xcode 7.3.1.
Also can repro the same thing on Xcode 8b5.

**Comment by nlutsenko** [comment]
From my investigation down the rabbit hole:
- the clipping is caused by smaller rects that TextKit for bounds of a text block
- `UILabel` is using `NSAttributedString - boundingRectWithSize:options:context:`
- That method lives in a private framework - `UIFoundation`, and the implementation doesn't seem to use TextKit

**Comment by ocrickard** [comment]
I'm not really sure where all these things are in ASDK, but can you try removing this line: https://github.com/facebook/AsyncDisplayKit/blob/aba05a747c9222de91de2a65e601393a7a284943/AsyncDisplayKit/TextKit/ASTextKitContext.mm#L56 ? I think that should just leave the default line fragment padding, which may help.

**Comment by ocrickard** [comment]
(I think that may help with the italic clipping issue, though at the cost of slightly larger padding around the text container for normal glyphs.

**Comment by nlutsenko** [comment]
That helps with italic clipping issue, indeed, by adding extra padding around the text.
Doesn't help with descender/ascender stuff though...

**Comment by ocrickard** [comment]
Yeah, looking at the code, the sizing looks correct to me. Let's add the text container inset, and pad. It's sad, but it seems like the simplest solution here.

**Comment by ocrickard** [comment]
Also, I'd be in favor of killing that lineFragmentPadding = 0. PR welcome.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#139
