### ISSUE TITLE
accessibleElements seems to fail in certain cases 

### ISSUE THREAD

**Issue by rvsrvs** [facebookarchive/AsyncDisplayKit#2141]
I have a situation where I'm putting the view of an accessible ASDisplayNode into the tableHeaderView of an ASTableNode.   Something like this:

```
        let wrapper = ASDisplayNode()
        wrapper.frame = CGRect(x: 0, y: 0, width: 320, height: 300)
        wrapper.backgroundColor = UIColor.blueColor()
        wrapper.isAccessibilityElement = false
        wrapper.accessibilityLabel = "wrapperNode"
        wrapper.accessibilityIdentifier = "wrapperNode"
        wrapper.userInteractionEnabled = true

...
        let topNode = ASTableNode()
        topNode.view.tableHeaderView = wrapper.view
        topNode.view.tableHeaderView?.frame = CGRect(x: 0, y: 0, width: 320, height: 300)

//        let topNode = ASDisplayNode()
//        topNode.addSubnode(wrapper)

        topNode.userInteractionEnabled = true
        topNode.backgroundColor = UIColor.purpleColor()
        topNode.accessibilityLabel = "topNode"
        topNode.accessibilityIdentifier = "topNode"
        topNode.isAccessibilityElement = false
```

wrapper contains accessible elements.  But when I run UITests those elements are not visible to the XCTestRunner.  If I comment out the ASTable lines and uncomment the ASDisplayNode lines, the accessible elements become visible just as you expect.

If I run the Accessibility Inspector in the simulator the accessible elements are visible to Inspector in both cases.  When I set the same views up as UIViews rather than as Nodes, they are also visible.  I can submit a test showing this if desired.

Why would things be different in a tableHeaderView?

**Comment by rvsrvs** [comment]
[AsdkAccessibility.zip](https://github.com/facebook/AsyncDisplayKit/files/439982/AsdkAccessibility.zip)

Attached is a test project showing the problem.  If you start the Accessibility Inspector on the simulator and run the test: 

```
testNodeTable() 
```
You will observe that the Acessibility Inspector sees the two accessible views, but that the XCTestRunner does not.  This test instantiates a NodeTableController instance

 If you run the test: testNodeView() you will see that the XCTestRunner DOES see the accessible views this time.  The only difference between the two cases is that in the first one, the accessible view is being added to the tableHeaderView rather than two a node.   Any thoughts welcome.

**Comment by paulcking** [comment]
It looks like setting tableView.tableHeaderView to a node.view makes the node’s accessibility hierarchy invisible for testing.  But… if you wrap the node in a plain UIView, all the nodes magically become visible in the accessibility hierarchy.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#143
