### ISSUE TITLE
layoutSpecThatFits is not sizing ASNodeCell properly

### ISSUE THREAD

**Issue by ghost** [facebookarchive/AsyncDisplayKit#2152]
Hello, I am trying to build an `ASTableNode` with dynamically sizing `ASCellNodes`. I am sizing my cells using the `layoutSpecThatFits` method, however, when I change my text for the `ASTextNodes` the size of the cell doesn't seem to change. All that happens is the subviews are pushed down and the cell is `clippedToBounds`? 

Here is what I am **hoping to achieve:**

<img width="312" alt="screen shot 2016-08-27 at 10 24 31 am" src="https://cloud.githubusercontent.com/assets/13897274/18022294/b537d638-6c41-11e6-979a-07d4cf0fb013.png">

Here is a description of the cell in detail:
- A picture (`ASImageNode`) is in the top left corner (the black square) that always has a size of `CGSize(width: 70, height: 70)`
- To the right of the picture is a small `ASTextNode` that is meant to **dynamically resize**, keeping a **fixed width** between the picture and right of the cell
- Underneath the small `ASTextNode` is larger `ASTextNode` that is pretty much exactly the same except bigger. Most importantly it is meant to **dynamically resize** while keeping a **fixed width**
- Underneath the picture and two main title `ASTextNodes`, is a list, with each line consisting of a `ASImageNode` for the icon and a `ASTextNode` for the text. It's important that these `ASTextNodes` can also dynamically resize in height, however their width is fixed.
- Underneath the list is a `ASButtonNode` which it's width will always fit the cell and it's height is always `40`
- Finally at the bottom of the cell is what I call a spacer, it's simply a `ASDisplayNode` that is darker than the cell background to give the appearance of separation between cells. It's width is always the width of the cell and it's height is always `8`

Currently when the text is small enough to fit on one line, the cell is sized correctly. However, if the text fills up more than one line of the `ASTextNode`, this is what happens:

<img width="312" alt="screen shot 2016-08-27 at 10 26 49 am" src="https://cloud.githubusercontent.com/assets/13897274/18022553/ee7729f6-6c43-11e6-9c90-83c8d2dc5b2a.png">

You can see all of it's subviews are pushed down in the cell, however it's height is not updating. Here is what I have tried doing to fix the problem:
- Setting `flexShrink = true` for the `ASTextNodes` and `ASStackLayoutSpecs`. I thought one possibility is `ASTextNodes` are still being calculated as one line (instead of multiple when there is a lot of text) and that setting `flexShrink = true` would cause that one line to condense into multiple. However, nothing seemed to change, and I feel like I have tried every single combination using `flexShrink` and `flexGrow` on all my nodes as well as `ASStackLayoutSpecs`.
- Wrapping my `ASTextNodes` in a `ASStaticLayoutSpec` and applying a `sizeRange` to them. This also seemed to do nothing as well?
- Spent the last 4 - 5 hours searching the internet for any solution viciously

The problem is probably to do with my `layoutSpecThatFits` method, so I'll post my code for that below to see if I am doing anything wrong? 

```
override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec {

        /* Set preferred size for all asimagenodes */
        image.preferredFrameSize = CGSize(width: 70, height: 70)
        locationIcon.preferredFrameSize = CGSize(width: 16, height: 16)
        payRateIcon.preferredFrameSize = CGSize(width: 16, height: 16)
        categoryIcon.preferredFrameSize = CGSize(width: 16, height: 16)
        typeIcon.preferredFrameSize = CGSize(width: 16, height: 16)

        /* I set this to 1000 because I don't know how to set it to device width without using UIScreen.mainScreen() which in the docs says is bad to call in this method (I could probably use sizeRange and wrap in static spec?) */
        apply.preferredFrameSize = CGSize(width: 1000, height: 40)
        spacing.preferredFrameSize = CGSize(width: 1000, height: 8)

        //The header spec (Picture & two text nodes)
        let titleSpec = ASStackLayoutSpec(direction: .Vertical, spacing: 4, justifyContent: .Start, alignItems: .Start, children: [smallTitle, largeTitle])
        let headerSpec = ASStackLayoutSpec(direction: .Horizontal, spacing: 8, justifyContent: .Start, alignItems: .Start, children: [image, titleSpec])

        //The description spec (list of icons & text nodes)
        let locationSpec = ASStackLayoutSpec(direction: .Horizontal, spacing: 8, justifyContent: .Start, alignItems: .Start, children: [locationIcon, location])
        let payRateSpec = ASStackLayoutSpec(direction: .Horizontal, spacing: 8, justifyContent: .Start, alignItems: .Start, children: [payRateIcon, payRate])
        let categorySpec = ASStackLayoutSpec(direction: .Horizontal, spacing: 8, justifyContent: .Start, alignItems: .Start, children: [categoryIcon, category])
        let typeSpec = ASStackLayoutSpec(direction: .Horizontal, spacing: 8, justifyContent: .Start, alignItems: .Start, children: [typeIcon, type])
        let descriptionSpec = ASStackLayoutSpec(direction: .Vertical, spacing: 8, justifyContent: .Start, alignItems: .Start, children: [locationSpec, payRateSpec, categorySpec, typeSpec])

        //The end spec (button & spacer)
        let endSpec = ASStackLayoutSpec(direction: .Vertical, spacing: 8, justifyContent: .Start, alignItems: .Start, children: [apply, spacing])

        //The full spec (condensing above specs together)
        let fullSpec = ASStackLayoutSpec(direction: .Vertical, spacing: 8, justifyContent: .Start, alignItems: .Start, children: [headerSpec, descriptionSpec, endSpec])

        //Inset whole spec (inset everything by 8)
        let insets = UIEdgeInsets(top: 8, left: 8, bottom: 8, right: 8)
        let insetSpec = ASInsetLayoutSpec(insets: insets, child: fullSpec)

        return insetSpec
}
```

I'm very new to `AsyncDisplayKit`, yet find it amazing. My table view is already at 60FPS by simply using the `ASTableNode` and `ASCellNode`. I'm not sure if I should be doing anything with my `ASTextNodes` because apparently they already have an intrinsic size? 

Here is the full source code for my `ASCellNode` class incase it's a problem with something else I'm doing?

[Check it out here](http://pastebin.com/DM8C4rFX)

Thank you to the guys over at `AsyncDisplayKit`, it's an impressive framework! I also appreciate all the effort for helping me to understand and fix my errors 😊

**Additional Notes**
- I'm using the latest version of the `AsyncDisplayKit` `Cocoapod`

**Comment by garrettmoon** [comment]
Hey @ghost if you're still having issues, would you mind trying the latest Texture and moving your issue here: https://github.com/TextureGroup/Texture/issues
