### ISSUE TITLE
Asset preview image generation failed error 

### ISSUE THREAD

**Issue by cdiscla** [facebookarchive/AsyncDisplayKit#2160]
Hello
i need to show videos inside a UIScrollView; for certain videos i get

2016-08-28 13:20:10.516 ProjName[330:40352] Asset preview image generation failed with 
error: Error Domain=AVFoundationErrorDomain 
Code=-11800 "The operation could not be completed" 
UserInfo={NSUnderlyingError=0x14e01e8f0 {Error Domain=NSOSStatusErrorDomain Code=-12983 "(null)"}, 
NSLocalizedFailureReason=An unknown error occurred (-12983), 
NSLocalizedDescription=The operation could not be completed}

My code is

```
 for video in items {
    print(video.author)
    print(video.video_link)
    let mainNode = ASDisplayNode()
    let videoNode = ASVideoNode()
    videoNode.asset = AVAsset(URL: NSURL(string:video.video_link)!)  //remote mp4 url
    videoNode.frame = CGRectMake(self.view.frame.size.width*CGFloat(index), 0,
                                 self.view.frame.size.width,
                                 self.scrollViewVideo!.frame.height)
    videoNode.shouldAutoplay = false
    videoNode.shouldAutorepeat = false
    videoNode.muted = true
    videoNode.placeholderEnabled=false
    videoNode.delegate=self

    videoNode.page=index



    //dispatch_async(dispatch_get_main_queue(), {
        mainNode.addSubnode(videoNode)
        self.scrollViewVideo.addSubnode(mainNode)
    //})

    self.displayNodes.append(mainNode)
    self.videoNodes.append(videoNode)
     index=index+1
}
```

The same videos that are not displayed here are correctly displayed in other ViewControllers.
Can anyone please help me?

**Comment by hannahmbanana** [comment]
@cdiscla: would it be possible to include a sample project so that we could see more of the code? cmd + D on the project folder to duplicate the project and remove any unnecessary code.

**Comment by cdiscla** [comment]
Thank you @hannahmbanana , i attach 2 files, the ASCollectionView and the ASCellNode file that contains the videos; i need to have a CollectionView with 2 columns that, when visible, play small videos taken by a url; if i use .shouldAutoPlay=true i get the Code=-11800 "The operation could not be completed" error. Thanks in advance for your help
[Archive.zip](https://github.com/facebook/AsyncDisplayKit/files/456301/Archive.zip)

**Comment by cdiscla** [comment]
No way to solve it? :-( In this case i need to remove videos and use static images, it's a sin because a wall full of playing videos is really amazing to see. But i can't believe there is no way to play visible small videos in a CollectionView.

**Comment by hannahmbanana** [comment]
@cdiscla: could you try asking on the #asvideonode channel of ASDK's slack (#1582)?

**Comment by garrettmoon** [comment]
Going to close this out since there hasn't been any further discussion.
