### ISSUE TITLE
Folder structure is overwhelming

### ISSUE THREAD

**Issue by lolgear** [facebookarchive/AsyncDisplayKit#2176]
I want suggest a simple folder structure.
- Framework
  - Targets
  - workspace
  - dependencies
  - Podfile if necessary.
- Classes
- Tests
  - Tests targets
  - workspace
  - dependency on ../Framework/
  - Podfile if necessary
- Examples
  - Example1
    - Target
    - workspace
    - dependency on ../../Framework/
    - Podfile if necessary
  - Example2
  - Example3

This structure could be considered and improved.

Now project has many ambiguous folders which don't simplify inspection.

**Comment by hannahmbanana** [comment]
@lolgear: Hmmm...we do have a lot of files in the root directory. :)  I'm not sure what can be done about this, but I'll look into it this week.

**Comment by hannahmbanana** [comment]
@maicki recently suggested that we move the examples to a different repository

**Comment by garrettmoon** [comment]
I think this has improved a bit, if you're still interested in improving this, would you mind opening a PR on the Texture repo? https://github.com/TextureGroup/Texture/pulls
