### ISSUE TITLE
Set frame for ASNetworkImageNode, without using layoutSpecThatFits

### ISSUE THREAD

**Issue by jonybur** [facebookarchive/AsyncDisplayKit#2191]
Hi all. I am learning to use ASDK, so excuse me if my question is a little bit trivial.

I am trying to set up an ASNetworkImageNode. Just like Instagram, in my test app the layout is a feed of images, some images are 1:1 but other ones have unknown aspect ratios.

I have an array of images, and exactly 1 px underneath each ASNetworkImageNode I want to draw the next image in the array. I know that the node's frame width must be equal to the screen's width, but the height of the node remains variable and unknown until the image gets downloaded.

Is it absolutely necessary to use measure and layoutSpecThatFits to achieve this? I am having a hard time trying to adapt my code to the CSS-esque type of layout ASDK normally uses.

Thank you.

**Comment by hannahmbanana** [comment]
@jonybur: A sample application would be really helpful to debug your issue. cmd + D on the project folder to duplicate it and strip out any unnecessary code before attaching it here.

Have you seen our [ASDKgram sample project](https://github.com/facebook/AsyncDisplayKit/tree/master/examples/ASDKgram)?

**Comment by jonybur** [comment]
Hey @hannahmbanana,

Thank you for your answer. I am attaching a sample project. For now I am just trying to focus on everything to look nice. I did saw the ASDKgram sample project, but I wanted to try to work my way into learning this technology without copying example code, alas, here's the result.
[ASDK-Q.zip](https://github.com/facebook/AsyncDisplayKit/files/467283/ASDK-Q.zip)

I appreciate the help!

**Comment by garrettmoon** [comment]
Going to close this out since it's community debugging and hasn't been commented on in a while.
