### ISSUE TITLE
Sticky header in ASCollectionNode hided when scroll

### ISSUE THREAD

**Issue by bimawa** [facebookarchive/AsyncDisplayKit#2238]
Hi guys, I'm create stick header for my ASCollectionNode. But if i scroll in deep my CollectionNode, header disappear. I think its related with cash and ADK think so header not in a visible range? What can i do for fix it?
[Video](http://take.ms/l4HSE)
[Sticky header implementation](https://gist.github.com/toblerpwn/5393460)
Summary:
ADK: **1.9.7**

**Comment by bimawa** [comment]
Detect calling  in _ASDisplayView.mm `didMoveToWindow` method, when i scroll.

**Comment by bimawa** [comment]
So i think i must prevent remove my supplementary node?

**Comment by bimawa** [comment]
Update to ADK 1.9.90 now header blinked and go to hide... researching...
[Video](http://take.ms/xfK2a)

**Comment by garrettmoon** [comment]
Since this is community debugging and it hasn't been commented on in a while, I'm going to close this issue. If you're still having trouble, consider joining our Slack channel for help! http://texturegroup.org/slack.html
