### ISSUE TITLE
Get Code Coverage Reporting Working

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#2422]
Note: Implementation on this may need to wait until #2418 

Code coverage was disabled a while back due to incompatibilities with Xcode 7.3.1. We still need to get it back on track.

For now let's just dump tools and ideas in here. Slather / Coveralls is the standard, but apparently they're both kind of abandoned IMO.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#147
