### ISSUE TITLE
Filter-Move Tasks Over from Ship

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#2434]
We used Ship as our internal issue tracker for a while. It didn't really provide enough value and it raised barriers to community entry so we're going to move everything to GitHub, in the open.

We should migrate any tasks that are still relevant from Ship and close the Ship account so we can all move on. This is somewhat low-priority compared to the critical 2.0 migration work we're all doing but it will be a nice, clean break.

cc @maicki @hannahmbanana @appleguy @garrettmoon

**Comment by garrettmoon** [comment]
@hannahmbanana is this completed? Can we close?

**Comment by hannahmbanana** [comment]
@garrettmoon - I only moved over the `2.0` tasks. There are `130` remaining tasks. I wasn't sure if we wanted to flood GitHub with all of those at once. Perhaps I'll just move the `80` `2.1` tasks over.

**Comment by garrettmoon** [comment]
Eeek. Yeah, lets only move over ones we have a concrete milestone for.

**Comment by hannahmbanana** [comment]
Status: waiting to bring over the 81 `2.1` Ship tasks until we launch `2.0`...for the sake of everyone's morale. :)

**Comment by hannahmbanana** [comment]
Some of the tasks in Ship are duplicates, but many are not.

**Comment by garrettmoon** [comment]
Going to close this out since we're already issue overloaded.
