### ISSUE TITLE
Simplify Text Shadowing by Using NSShadowAttributeName

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#2510]
Currently our shadowing is implemented by `ASTextKitShadower`. We can simplify our text shadowing (and improve performance!) by using NSShadowAttributeName. During our rendering, if they specify a shadow on the node, we should add the shadow attribute into the string (anywhere it isn't already set.)

Considerations:
- We should check if NSShadowAttributeName affects sizing calculations – whether the shadow outset is included automatically or not.
- We should avoid allocating NSShadow objects whenever possible.

**Comment by hannahmbanana** [comment]
I for one, am SUPER EXCITED to see @Adlai-Holler's new ASTextNode improvements coming soon in Spring '17!

**Comment by Adlai-Holler** [comment]
Me too! God that guy is so _handsome!_

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#150
