### ISSUE TITLE
Support for Table View Section Headers and Footers

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#2525]
This is something that many users have requested. It would be reasonably easy to implement this using `ASCollectionDataController`, and treating headers/footers as supplementary elements.

We should add new API into `ASTableDataSource` that mirrors `ASCollectionDataSource` i.e. `tableNode:nodeBlockForHeaderInSection:`, `tableNode:nodeForHeaderInSection:` and `tableNode:constrainedSizeForHeaderInSection:` and the same methods for footers.

**Comment by xilin** [comment]
May I ask what's the the best way to add table view section headers and footers currently?

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#152
