### ISSUE TITLE
[ASImageNode] add support for tintable template images

### ISSUE THREAD

**Issue by IvanChan** [facebookarchive/AsyncDisplayKit#2533]
Like code below, the image shows in button should be red. But it will be always black no matter what I did.

It works well if I change ASButtonNode to UIButton.

ASImageNode also fail.

```
    UIImage *image = [UIImage imageNamed:@"snow_flower.png"];
    image =  [image imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
    self.asBtn.frame = CGRectMake(30, 30, 100, 100);
    [self.asBtn setImage:image forState:ASControlStateNormal];
    [self.view addSubnode:self.asBtn];
    [self.asBtn setTintColor:[UIColor redColor]];
```

**Comment by hannahmbanana** [comment]
@IvanChan - this isn't currently implemented, however, we'd be happy to accept a pull request if you would like to implement this!

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#153
