### ISSUE TITLE
[ASNetworkImageNode] Placeholder does not fade out for network images

### ISSUE THREAD

**Issue by kimshako** [facebookarchive/AsyncDisplayKit#2557]
Talked with @appleguy with this issue on slack on Nov 5.

## Reproduce
- examples_extra/Placeholders [diff.txt](https://github.com/facebook/AsyncDisplayKit/files/573641/diff.txt)
- Changed `ASImageNode` -> `ASNetworkImageNode`
- Loaded network image
- Removed ForwardWorkaround in `SlowpokeImageNode`

## Expected
Placeholder image fade out with `placeholderFadeDuration` and `placeholderFadeEnabled` set.

## Current
- This issue is not occurring 100% time. Refer to the gif image below: first attempt show animation properly, other attempt does not.
- with ForwardWorkaround and for duration over 0.1s, the issue is not occurring.

![bug](https://cloud.githubusercontent.com/assets/1745342/20035401/ae36bd4e-a3b0-11e6-8977-2a9df0839029.gif)

## Affected Version (checked)
- 1.9.81
- 1.9.90
- 1.9.92
- 2.0-beta.1

**Comment by garrettmoon** [comment]
I'll try and take a look at this one.

**Comment by EviluS** [comment]
@kimshako A quick workaround is to adopt the `ASNetworkImageNodeDelegate` and implement the `imageNode:didLoad:` method  where you can add a CATransition to the node layer.

`CATransition *transition = [CATransition animation];`
`[transition setDuration:0.25];`
`[transition setTimingFunction:[CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseInEaseOut]];`
`[transition setType:kCATransitionFade];`
`[[self layer] addAnimation:transition forKey:@"AsyncImageNodeDisplayTransition"];`

**Comment by kimshako** [comment]
@EviluS Thank you for your workaround. I had been using similar approach using UIView.animate(), though, this solution looks better to me.

**Comment by appleguy** [comment]
We do need to fix this very soon, but can't squeeze it in for 2.0.  Higher priority for 2.0.1.

**Comment by appleguy** [comment]
@garrettmoon I'd recommend that we punt this to 2.0.2 and investigate it in January.

**Comment by garrettmoon** [comment]
Yeah, sadly I couldn't get to this, will investigate as soon as I'm able!

**Comment by hannahmbanana** [comment]
@garrettmoon - I recall you mentioning working on placeholders recently. Was that related to this Issue?

**Comment by appleguy** [comment]
@garrettmoon This seems like a good candidate to punt to 2.1.  It would be really great to fix, though!

**Comment by garrettmoon** [comment]
We'd like to overhaul the placeholder system soon. Unscheduling and assigning to @Adlai-Holler

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#154
