### ISSUE TITLE
[ASDisplayNode] Escalate drawingPriority of nodes when performing recursivelyEnsureDisplaySynchronously:YES.

### ISSUE THREAD

**Issue by appleguy** [facebookarchive/AsyncDisplayKit#2575]
Doing this would prevent excessive waits when UI, like tapped states, need to perform a synchronous display.  If the display queue is very busy and the device is slow, especially on an older iPad with a lot of content, it can take a few full seconds to clear the display queue.

@nguyenhuy we do see this in Pinterest (it's rare but happens consistently enough for a small set of users with these older devices).  Can you think of a simple way to artificially boost drawingPriority for these nodes?  Can we add ~10 to the priority at the point that the priority is checked, or add to it in the getter method of each node if they're able to efficiently check that a synchronous display is ongoing?

5  libsystem_pthread.dylib        0x22bf50b9 pthread_cond_wait
6  Pinterest                      0x7f6087 ASDN::Condition::wait(ASDN::Mutex&) (ASThread.h:278)
7  Pinterest                      0x7f602d ASAsyncTransactionQueue::GroupImpl::wait() (_ASAsyncTransaction.mm:305)
8  Pinterest                      0x7f7399 -[_ASAsyncTransaction waitUntilComplete] (_ASAsyncTransaction.mm:488)
9  Pinterest                      0x83e393 recursivelyTriggerDisplayForLayer(CALayer*, signed char) (ASDisplayNode.mm:2255)
10 Pinterest                      0x83e523 -[ASDisplayNode _recursivelyTriggerDisplayAndBlock:] (ASDisplayNode.mm:2272)
11 Pinterest                      0x6696c1 -[PITapStateAnimationController prepareSubnodesForTapStateAnimation] (PITapStateAnimationController.m:453)
12 Pinterest                      0x666925 -[PITapStateAnimationController setDepressed:] (PITapStateAnimationController.m:134)
13 Pinterest                      0x3611c5 -[ASControlNode(PIAdditions) controlEventUpdated:] (ASControlNode+PIAdditions.m:68)
14 Pinterest                      0x821f43 __55-[ASControlNode sendActionsForControlEvents:withEvent:]_block_invoke (ASControlNode.mm:433)
15 Pinterest                      0x820dd5 _ASEnumerateControlEventsIncludedInMaskWithBlock(unsigned int, void (unsigned int) block_pointer) (ASControlNode.mm:454)
16 Pinterest                      0x821bfb -[ASControlNode sendActionsForControlEvents:withEvent:] (ASControlNode.mm:436)
17 Pinterest                      0x820023 -[ASControlNode touchesBegan:withEvent:] (ASControlNode.mm:152)
18 Pinterest                      0x7fad39 -[_ASDisplayView touchesBegan:withEvent:] (_ASDisplayView.mm:235)
19 UIKit                          0x27491b97 _UIGestureRecognizerUpdate

**Comment by appleguy** [comment]
Scheduling 2.0 for now - we should punt if this takes more than a couple hours to fix.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#155
