### ISSUE TITLE
[ASTextNode] Unnecessary Text Layout in ASTextKitRenderer

### ISSUE THREAD

**Issue by b3ll** [facebookarchive/AsyncDisplayKit#2600]
Currently ASTextKitRenderer (ASDK 1.9.92) uses the bounds of the text container to render the required glyphs, rather than the bounds passed in through `-drawInContext:bounds:`.

````
NSRange glyphRange = [layoutManager glyphRangeForBoundingRect:CGRectMake(0,0,textContainer.size.width, textContainer.size.height) inTextContainer:textContainer];
    
[layoutManager drawBackgroundForGlyphRange:glyphRange atPoint:shadowInsetBounds.origin];
[layoutManager drawGlyphsForGlyphRange:glyphRange atPoint:shadowInsetBounds.origin];`
````

Is there any reason for this?

I'm currently laying out text in a `UIScrollView`, which can change dynamically, and I'd rather it not redraw the entire scrollview's `-contentSize` of glyphs, since that can be extremely expensive. For larger sets of text, it's actually impossible to draw the whole set since it ends up being so memory intensive.

**Comment by garrettmoon** [comment]
I don't think this is as urgent as a P1, but we should definitely prioritize for 2.1

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#156
