### ISSUE TITLE
[Documentation] Add visuals to describe data source thread safety (important for UIKit and ASDK alike).

### ISSUE THREAD

**Issue by appleguy** [facebookarchive/AsyncDisplayKit#2618]
See this discussion on Slack - we can demonstrate the proper technique in ASDKgram (I think it already does it correctly, but we should check) and draw some quick diagrams and create a Documentation page to describe why this is important for both UIKit and ASDK, for any app that updates data from the network on a background queue.

> 
> tettoffensive	[12:16 PM]  
> Hi, in 1.9.90 `tableViewLockDataSource` and tableViewUnlockDataSource` are deprecated
> 
> [12:17]  
> Is there a different way to accomplish preventing the datasource from updating while the ASTableView is reloading?
> 
> [12:18]  
> it causes crashes in our app when the tableview is displaying the cells while the data source is updating from a network request
> 
> appleguy	[12:48 PM]  
> @afilipowicz hmm that's strange, it's not supposed to animate the scroll to the new position.  Maybe take a quick look at the implementation of the adjustsContentOffset and see if you can tweak it to use a non-animated scroll - it's possible it regressed recently?  It used to be seamless / not animate
> 
> [12:49]  
> @tettoffensive hey there.  It sounds like you need a regular lock at the application level
> 
> [12:49]  
> the old lock / unlock data source was about controlling an internal ASDK lock.  This is a very old API and was needed before nodeBlocks were devised
> 
> [12:50]  
> but nowadays, all the APIs are called on the main thread - e.g. all the nodeBlocks are captured on the main thread - so from the ASDK <-> App interface there is no need for locking serialization
> 
> [12:51]  
> however, if your app has an array or something else that is mutable or can be replaced on a background thread, then you have a shared state situation where the main thread can be reading from something that is being written by a background thread.  In all such cases, some form of serialization is necessary.
> 
> The best comparison is with UIKit - the same situation will cause crashes, because the main thread may be requesting info from the dataSource and _during_ those calls any background thread could come in and change the data (edited)
> 
> [12:53]  
> The simplest fix for most apps is to do a dispatch_async to the main queue — of course AFTER any expensive JSON parsing, model object creation, etc.  But the actual insertion into the datasource, or replacing an array used as the datasource, that very last operation should happen on the main thread.  This is a simple way to guarantee that no datasource activity is going on, because it always happens during one runloop (meaning, a dispatched-to-main block can't run until after the fetches from the datasource)
> 
>

**Comment by hannahmbanana** [comment]
bumping until I'm done with product code

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#158
