### ISSUE TITLE
[Unit Testing] Add test to exercise "manual bounds override" in layout pass.

### ISSUE THREAD

**Issue by appleguy** [facebookarchive/AsyncDisplayKit#2633]
The tests pass both with, and without the size-check logic discussed in the constrainedSizeForLayoutPass method:

https://github.com/facebook/AsyncDisplayKit/pull/2597#discussion_r88559287

If these checks are essential, the tests should fail when they are removed.

**Comment by Adlai-Holler** [comment]
Moving to 2.0.1 after discussion with the team. This is very important but we have to prioritize for the milestone @garrettmoon

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#160
