### ISSUE TITLE
[ASDisplayNode] placeholder calculations are done before calling `calculatedLayoutDidChange:`

### ISSUE THREAD

**Issue by yans** [facebookarchive/AsyncDisplayKit#2685]
the placeholder calculations done [here](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L2340), does not call `calculatedLayoutDidChange:` before hand. despite the fact that the layout calculation is guaranteed to be done before that placeholder call. this may cause the placeholder image is to be generated with the wrong parameters, especially if it depends on layout calculations.

**Comment by hannahmbanana** [comment]
Thanks for filing this issue @yans! Btw - are you at Pinterest? Your name looks familiar. :)

**Comment by hannahmbanana** [comment]
How does this affect Pinterest?

**Comment by yans** [comment]
just realized the link is out of date
here's the updated one: https://github.com/facebook/AsyncDisplayKit/blob/361f7be6ed9ec6287b060d530207cea1837caed0/AsyncDisplayKit/ASDisplayNode.mm#L2340

**Comment by hannahmbanana** [comment]
Phabricator diff D136116 - circle images were experience flashes of corners for the placeholder

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#161
