### ISSUE TITLE
[Automatic Subnode Management] Improvements

### ISSUE THREAD

**Issue by hannahmbanana** [facebookarchive/AsyncDisplayKit#2700]
- [x] enable by default
- [ ] support manually inserted nodes
- [ ] support reordering of managed nodes - Levi: "Implicitly managed nodes should be no longer managed by the diffing algorithm if a user manually moves the position of a node via insertNodeAtIndex:, etc. This will reduce the complexity of inconsistent state that can arise when the developer interfaces with the hierarchy."
- [ ] Relevant ASM bug - #2825

**Comment by garrettmoon** [comment]
I think this has all been taken care of!
