### ISSUE TITLE
Rethink / Improve current locking strategy 

### ISSUE THREAD

**Issue by hannahmbanana** [facebookarchive/AsyncDisplayKit#2702]
Adlai: 
"Recursive locks are in general not a great idea. We should rethink our locking strategy and maybe introduce a “property” lock and “layout” lock. This needs a very thought out solution as this is a core part of the framework.

Why recursive locks are not the best idea: 
http://www.fieryrobot.com/blog/2008/10/14/recursive-locks-will-kill-you/
http://www.zaval.org/resources/library/butenhof1.html"

**Comment by garrettmoon** [comment]
We've significantly refactored locking and I don't think we still need an issue like this tracking locking – we're always making improvements.
