### ISSUE TITLE
Height of pages is wrong if a fullscreen ASPagerNode has scrollable direction of UICollectionViewScrollDirectionVertical

### ISSUE THREAD

**Issue by maicki** [facebookarchive/AsyncDisplayKit#2742]
If a fullscreen `ASPagerNode` is embedded in an `ASViewController` and the `scrollDirection` is `UICollectionViewScrollDirectionVertical` the height of the node is not correct.

The reason for that is that if the bounds changes of the `ASViewController` in `- (void)layer:(CALayer *)layer didChangeBoundsWithOldValue:(CGRect)oldBounds newValue:(CGRect)newBounds` in `ASCollectionView` we don't re-layout the nodes as the bounds changed in the scrollable direction, but in fact in this case the bounds changed in the scrollable direction.

**Comment by hannahmbanana** [comment]
What are the next steps? Should we document the work around or prioritize this for fixing?

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#162
