### ISSUE TITLE
[Performance] ASRunloopQueue should have "runtimeInterval" besides just "batchSize", esp. for Deallocation.

### ISSUE THREAD

**Issue by appleguy** [facebookarchive/AsyncDisplayKit#2766]
Particularly for our new Dealloc2Main replacement, which sends a relatively large number of objects into an ASRunloopQueue for deallocation on main, we should add a simple timer facility to allow deallocating as large a number of these objects as possible per runloop _without_ having significant impact on framerate.

It makes sense for this to be a separate ASRunloopQueue from some other workloads, because it's even more opportunistic (although all runloop queue work has a certain opportunistic element).  Ideally:

- Flush the queue completely, or accelerate flushing significantly (allow frame drops) in case of a memory warning.
- In other conditions, obey a runtimeInterval of something like 3-5ms to limit frequency and severity of frame drops.  This will be a variable number of objects depending not only on the device, but greatly depending on the object types being destroyed.
- Importantly, it would be ideal to allow ASRunloopQueue objects to coordinate with one another and at a minimum weigh the total runtime of their work.  For example, a two-class system would work well: the dealloc queue should defer to / always count work performed by any other ASRunloopQueue as subtracted from the runtime it has to work with, such that it may entirely skip certain runloop cycles.  Since the loop turns so rapidly due to the immediate signalling, this should not create issues with queue drain times, especially if the total object limit is higher by basing off of times.

The time limit would be based on an individual turn of the runloop for now.  In the future, it could be made more advanced and effective by relating in some way to the CADisplayLink.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#163
