### ISSUE TITLE
[Investigation] Calling setContentInset: can create infinite layout loop

### ISSUE THREAD

**Issue by appleguy** [facebookarchive/AsyncDisplayKit#2768]
It's not technically valid to call this from within layoutSpecThatFits:, but we should do two things:

- Add an override in setContentInset: and setContentOffset: to assert that they are called on the main thread, and trampoline them to main in case of production.

- Investigate if we can reproduce this in a test case with setContentInset: being inside -layout, such that this might occur even if the code is not incorrectly in the layoutSpec method.

In the case that we can build a unit test for the latter, then, I think we simply need to adapt the logic inside setNeedsLayoutFromAbove: to have a more explicit loop detection.  Right now it can detect loops occurring ACROSS separate runloops, which is even harder to detect, if they are thrashing the .bounds value.  But in this case we simply need to set an instance variable for "inside setNeedsLayoutFromAbove" and ignore further calls to it during that same layout pass?

https://fabric.io/pinterest6/ios/apps/pinterest/issues/58506d6c0aeb16625bf4d5a7

**Comment by maicki** [comment]
Moving this out of the 2.0.2 milestone due to time constraints.

**Comment by garrettmoon** [comment]
This will need to be fixed after the overhaul of the layout system. Clearing milestone for now, it'll be addressed soon as it's still a P1.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#164
