### ISSUE TITLE
applyPendingSections: May Be Called with Mismatched Index Set and Array

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#2772]
In some cases, the count of our `_pendingSections` array may not match the count of the `sectionIndexes` set passed into this method from `willReloadDataWithSectionCount:`. This was observed in 2253c9d8205b0af9c65b576c5db7aaec269afd70 . I would call it "somewhat rare" – about 12% as common as our most common aggregation – so it will be tough but probably possible to reproduce.

<img width="980" alt="screen shot 2016-12-14 at 11 46 31 am" src="https://cloud.githubusercontent.com/assets/2466893/21191402/fc822a96-c1f2-11e6-841f-b84fd14ecfa8.png">

https://fabric.io/pinterest6/ios/apps/pinterest/issues/585071d40aeb16625bf4f42b

**Comment by zrxq** [comment]
Our app crashes on this ~200 times per day, according to Crashlytics. Is there any way I can help fixing this? (given I don't have a good understanding of how ASDK works internally)

**Comment by Adlai-Holler** [comment]
Haven't seen this thing in forever. @zrxq are you seeing this on the latest Texture?

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#165
