### ISSUE TITLE
numberOfSections/numberOfItemsInSection: May Be Incorrect During constrainedSizeForNodeOfKind/nodeBlockForItem:

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#2779]
These methods are called _during_ the setup of the node contexts, and so you will see the old values if you read them at this time.

To address this, we could reimplement `numberOfSections` and `numberOfItemsInSection:` using `itemCountsFromDataSource` instead of the contexts array.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#166
