### ISSUE TITLE
Replace UICollectionViewLayout Subclassing with ASDK-Synced Layout Object

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#2780]
Right now the user subclasses `UICollectionViewLayout` and talks directly to the collection view. This brings a number of issues:

- If the layout talks to the data source/delegate, it may be out-of-date while edit operations propagate through the data controller.
- We can't know the layout for nodes until we insert them into the UICollectionView. 
- We have to measure all nodes in advance, even if the layout doesn't care!
- It would be nice to do the layout off-main!

I've thought through the requirements a bit, I'll add them into this task later.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#167
