### ISSUE TITLE
ASTableNode and contentSize calculation

### ISSUE THREAD

**Issue by stephenkopylov** [facebookarchive/AsyncDisplayKit#2788]
In ASDK 1.9.x I have used synchronous ASTableView/Node reloading through "reloadImmediately" to get proper tableView.contentSize.

How can I reach same functionallity with ASDK 2.0? 

I have tried to subscribe for tableNode.view.contentSize updates through KVO, but it fires to many times =(

Maybe there is some method that fires once after tableNode completes contentSize calculations? Or maybe ASTableNode may do all the calculations synchronous?

Thanks in advance and excuse me for my English

**Comment by maicki** [comment]
@stephenkopylov You could try: `tableNode.reloadData()`; `tableNode.waitUntilAllUpdatesAreCommited()`;

**Comment by hannahmbanana** [comment]
For more information on how ASTableNode works behind the scenes, checkout this video: https://youtu.be/yuDqvE5n_1g

**Comment by stephenkopylov** [comment]
@maicki  @hannahmbanana Thank you! I will try **waitUntilAllUpdatesAreCommited**

**Comment by hannahmbanana** [comment]
@stephenkopylov - Just to be clear, I think the strategy that @maicki is suggesting is to call both one after another.

**Comment by graceydb** [comment]
CGSize oldSize = self.tableNode.view.contentSize;
[self.tableNode reloadData];
[self.tableNode waitUntilAllUpdatesAreCommitted];
CGSize newSize = self.tableNode.view.contentSize;

OldSize,newSize difference between the two is the same or less. WaitUntilAllUpdatesAreCommitted don't work or I don't understand

**Comment by nareksedrakyan1990** [comment]
dispatch_async(dispatch_get_main_queue(), ^{
               CGFloat diff = self.tableNode.view.contentSize.height - lastContentSizeHeight;
            });

**Comment by stephenkopylov** [comment]
It works! =)
But this way only:

``` objectiveC
[self.tableNode waitUntilAllUpdatesAreCommitted];
[self.tableNode reloadData];

CGSize size = self.tableNode.view.contentSize;
```

**Comment by garrettmoon** [comment]
Going to close this issue as it appears there's a work around.
