### ISSUE TITLE
Layout transition doesn't resize the title of ASButtonNode properly

### ISSUE THREAD

**Issue by tomizimobile** [facebookarchive/AsyncDisplayKit#2789]
When using `transitionLayout(withAnimation: true, shouldMeasureAsync: true, measurementCompletion: nil)`, the `titleNode` of an ASButtonNode isn't resized properly. This can be worked around by either overriding `-animateLayoutTransition` and calling `setNeedsLayout` on the ASButtonNode, or by using `shouldMeasureAsync: false`.

Some previous history of this issue is here: https://github.com/facebook/AsyncDisplayKit/issues/2713

**Comment by ngoctr** [comment]
I got a similar issue but in my case the image of the button disappear (as there is no size change for the button) after the transition even with `shouldMeasuerAsysnc: false`. if I go to Xcode -> Debug -> View Debugging -> Show View Frames then the image reappears again. Very weird.

**Comment by hannahmbanana** [comment]
@tomizimobile and @ngoctr - which commit / version of ASDK are you using?

**Comment by tomizimobile** [comment]
@hannahmbanana looking at the linked issue, I guess I must've been using https://github.com/facebook/AsyncDisplayKit/commit/7861c63a680f516fc69cd083d462469f0a175697, and I believe everything up to master at that time (Dec. 5) showed the issue. I haven't checked to see if this is still a problem since opening the issue

**Comment by garrettmoon** [comment]
Going to close out, please re-open on Texture if this is still an issue: https://github.com/texturegroup/texture/issues
