### ISSUE TITLE
Pager Node Test May Fail Spuriously

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#2818]
From #2812, there is a CI failure that appears to be unrelated to the code changed:

http://jenkinsmaster-vpc-007.ec2.pin220.com/job/AsyncDisplayKit-PRs/1372/console

<img width="721" alt="screen shot 2016-12-21 at 12 53 31 pm" src="https://cloud.githubusercontent.com/assets/2466893/21400107/8300747c-c77c-11e6-81a3-6df5496a3807.png">

@maicki Would you take a look at this and see if there's a possible race condition? I'll restart the build on that PR and see if we get it again.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#169
