### ISSUE TITLE
Node Subtrees that Use Automatic Subnode Management May Not Get Interface State Updates

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#2825]
If you have, say, a cell node that uses automatic subnode management, its subnode insertions won't be applied until the first UIKit layout pass, which will happen after the node enters the display range.

So, for example network image nodes won't start fetching their images until after async display starts.

This is obviously tricky. Especially if we want to account for the possibility that a cell node that is outside the display range could change its automatically managed subtree (i.e. call `setNeedsLayout` and change its return value from `layoutSpecThatFits`) at any time.

We could say that any node that is outside the window hierarchy but in the `MeasureLayout` (or `Preload`) range should perform layout whenever `setNeedsLayout` is called. The measurement could be run asynchronously, and then the node could call `__layout` on itself.

**Comment by Adlai-Holler** [comment]
cc @appleguy @garrettmoon @maicki

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#170
