### ISSUE TITLE
Synchronous Cell Nodes May Trigger Assertion Failure When Deleted from Collection

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#2855]
If you create a cell node with `-initWithViewBlock`, it will not be kept alive by being in the view hierarchy (like a normal node) and so if you delete that item while it's visible, you may hit the assertion in `didEndDisplayingCell:` that the node is non-nil, because the node will have been released by the data controller before the animation finishes.

Probably our best bet is to have the `_ASCollectionViewCell` maintain a strong reference to its node, and clear that in `didEndDIsplayingCell:`. Right now the `cell -> node` relationship is `weak`.

This is a pretty rare usage, assigning somewhat low priority.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#171
