### ISSUE TITLE
ASTableNode with flexGrow = 1.0 view flicks on resizing

### ISSUE THREAD

**Issue by 8ofproject** [facebookarchive/AsyncDisplayKit#2874]
Layout:
I have vertical stack in my view controller node: 3 subnodes and ASLayoutSpec spacer for keyboard management
Two nodes have constant height (via `style.height`).
Spacer change height according to keyboard size on screen (0 when there is no keyboard on screen). (via .wilShow, .willHide notifications, if does matter).
The rest of the view controller's node should be TableNode.

Problem: 
Can't make layout both responsive to spacer height changes _and_ visually appealing on keyboard show/hide.

Tried to approaches:
**(1)** with a help of style.flexGrow = 1.0

When keyboard starts showing the TableNode flicks and error messages like:
`Cannot calculate size of node: constrainedSize is infinite and node does not override -calculateSizeThatFits: or specify a preferredSize. Try setting style.preferredSize. Node: <<ASTableNode...` starts to pop out in console.

I've also tried to set `style.preferredSize` inside `layoutSpecBlock` like this:
`let tableNodeHeight = ViewController node height - top node height - bottom node height - keyboard spacer height
tableNode.style.preferredSize = CGSize.init(width: widthFrom, height: tableViewHeight)
`
No errors, no flicks but TableNode stopped change its height on keyboard show-hide.

**(2)** recalculate TableNode height manually
+ delete line `style.flexGrow = 1.0` for TableNode
+ inside `layoutSpecBlock`set `style.height` for every element: two nodes, spacer and rest for TableNode

Flick stops but resizing on keyboard-show also stops.

ASDK 2.0.1
iOS 10+ Simulator and real device

Looks like related to issue https://github.com/facebook/AsyncDisplayKit/issues/2055

**Comment by 8ofproject** [comment]
I feel like example code will definitely help:
[KeyboardSample.zip](https://github.com/facebook/AsyncDisplayKit/files/691792/KeyboardSample.zip)

You can show/hide software keyboard in iOS Simulator via `Cmd+K` shortcut.

All relayout happens in:
_AddressUIFactory.swift_'s 
_setupNodeLayout(...)_
on line ~ 40

**Comment by 8ofproject** [comment]
Just in case:
Screenshot of how layout changes on keyboard show (flicks very fast so I can't catch it).
![change-on-keyboard](https://cloud.githubusercontent.com/assets/6408861/21746149/624a1664-d54d-11e6-9153-39d97b400786.png)

**Comment by 8ofproject** [comment]
Just want to update issue status:
After v. 2.2 flick effect is faster and a little bit less noticeable.
But still visible.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#172
