### ISSUE TITLE
Slightly Flaky ASNetworkImageNode Test

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#2898]
We've seen `testThatProgressBlockIsSetAndClearedCorrectlyOnVisibility` [fail](http://jenkinsmaster-vpc-007.ec2.pin220.com/job/AsyncDisplayKit/462/) randomly on the master CI (which runs 20 iterations of the unit tests.)

I've spent some time looking at the code for this test, but I cannot find a way for the code to fail. But fail it does! I'll open a diff to disable the test for the time being.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#175
