### ISSUE TITLE
[ASPagerNode] rotation issue

### ISSUE THREAD

**Issue by Antowkos** [facebookarchive/AsyncDisplayKit#2924]
Hi! I already wrote about it in slack, but nobody tell me what to do.

I try to implement simple image viewer (`ASViewController` with `ASPagerNode` in it). Every "page" is `ASViewController` with `ASNetworkImageNode` in it. I create image node this way:
```
    lazy var imageNode: ASNetworkImageNode = {
        let node = ASNetworkImageNode()
        node.contentMode = .scaleAspectFit
        node.isLayerBacked = true
        return node
    }()
```
Everything works fine until I try to rotate device. There are 2 issues appears:
1. If I open not first image (It happens with using `scrollToPage(at:,animated:)` function) and rotate device then I see this 
![simulator screen shot 24 2017 9 10 09](https://cloud.githubusercontent.com/assets/3423650/22232657/f9d7c39a-e214-11e6-8704-0c6ff2453860.png)
This issue happens until I scroll to next or previous page.
2. The main issue is that image renders wrong after rotation 
![simulator screen shot 24 2017 8 47 42](https://cloud.githubusercontent.com/assets/3423650/22232707/5557902e-e215-11e6-9356-0307c0e572a6.png)
![simulator screen shot 24 2017 8 47 44](https://cloud.githubusercontent.com/assets/3423650/22232708/55582bec-e215-11e6-8d7b-e36e2b196d20.png)
As you can see image become smaller. But if I scroll some pages forward and then back to this "page" everything lays out normally
![simulator screen shot 24 2017 9 19 33](https://cloud.githubusercontent.com/assets/3423650/22232857/419aaeee-e216-11e6-9225-863edbb9a5c6.png)

**Comment by hannahmbanana** [comment]
@Antowkos - What version of ASDK are you using? Would you be able to put together a sample project for us? It will help us debug the issue much more quickly.

**Comment by Antowkos** [comment]
@hannahmbanana Thanks for reply! 
The latest one. I will try to make sample project for you ASAP.

**Comment by Antowkos** [comment]
@hannahmbanana Here is example project with that bug. 
[ASPagerNodeBug.zip](https://github.com/facebook/AsyncDisplayKit/files/728533/ASPagerNodeBug.zip)

Also there is 1 more bug, related to this part of code 
```
func pagerNode(_ pagerNode: ASPagerNode, constrainedSizeForNodeAt index: Int) -> ASSizeRange {
    if pagerNode.isNodeLoaded {
        return ASSizeRangeMake(pagerNode.view.bounds.size)
    }
    return ASSizeRangeMake(pagerNode.bounds.size)
}
```

If you comment one of `return` you will see that scrolling is terrible.

**Comment by Antowkos** [comment]
For those who face with this situation while it isn't fixed I found workaround for both bugs.

1. Bug with shrinking image after rotation can be fixed by using `ASRatioLayoutSpec`. I subclass `ASNetworkImageNode` and after loading image I calculate `ratio` of the image and force `supernode` to layout:
```
func imageNode(_ imageNode: ASNetworkImageNode, didLoad image: UIImage) {
        ratio = image.size.height / image.size.width
        invalidateCalculatedLayout()
        supernode?.setNeedsLayout()
}
```
The supernode use `ratio` by wrapping `imageNode` into `ASRatioLayoutSpec`:
```
let ratioSpec = ASRatioLayoutSpec(ratio: imageNode.ratio, child: imageNode)
```
2. Bug with wrong scroll position after rotation is much trickier. 
In my view controller which contains my `pagerNode` I do the following:
```
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
    isRotationInProgress = true
    pagerNode.view.collectionViewLayout.invalidateLayout()
    coordinator.animate(alongsideTransition: { _ in
    }) { _ in
        pagerNode.scrollToPage(at: currentPageIndex, animated: false)
        isRotationInProgress = false
    }
}
```
I use the flag `isRotationInProgress` only by one reason - rotation causes resetting of `pagerNode`'s `currentPageIndex` or it is a bug of `ASPagerNode` and it is not updating after calling a method `scrollToPage(at:, animated:)` properly. Anyway I was forced to use my own `currentPageIndex` property. And I update it this way:
```
func collectionNode(_ collectionNode: ASCollectionNode, willDisplayItemWith node: ASCellNode) {
    if !isRotationInProgress {
        currentPageIndex = pagerNode.indexOfPage(with: node)
    }
}
```

**Comment by garrettmoon** [comment]
I think this has been fixed, can you re-open on the new Texture repo if not: https://github.com/texturegroup/texture/issues
