### ISSUE TITLE
[ASNetworkImageNode] PINRemoteImage and PINCache not works via Carthage

### ISSUE THREAD

**Issue by Antowkos** [facebookarchive/AsyncDisplayKit#2925]
There are many issues related to work of `PINRemoteImage` and `PINCache` via Carthage already, but all of them are linked to each other and hasn't any solutions. For now I pretty sure that it is impossible to use `PIN` stuff via Carthage with `PIN_REMOTE_IMAGE` preprocessor macros in the way it is now in Cocoapods because preprocessor macroses can **not** affect on already built framework. So i see 2 possible options that can help with this issue: 

1. Build framework with that macros enabled (unfortunately i can’t test it right now because `PINRemoteImage` can’t be build with Carthage) 
2. Stop using preprocessor macros `PIN_REMOTE_IMAGE` at all and use `PIN`s as necessary dependencies. Actually `PIN`s will be necessary in both cases and they are necessary dependencies for default installation already (no matter Cocoapods or Carthage). 

I prefer the second solution, because for most projects standard behaviour of `ASNetworkImageNode` for caching and downloading images isn’t enough.

**Comment by QuynhNguyen** [comment]
There is an attempt to fix this problem https://github.com/facebook/AsyncDisplayKit/pull/1797/files but I believe that is for Objc project only.

**Comment by Antowkos** [comment]
Guys! I fix the issue with building ASDK via Carthage. Caching is working now. Please, check my PR.

The one issue is left though. `ASPINRemoteImageDownloader` has this checking for working with animated image via `PIN` library
```
#if __has_include (<PINRemoteImage/PINAnimatedImage.h>)
#define PIN_ANIMATED_AVAILABLE 1
#import <PINRemoteImage/PINAnimatedImage.h>
#import <PINRemoteImage/NSData+ImageDetectors.h>
#import <PINRemoteImage/PINAlternateRepresentationProvider.h>
#else
#define PIN_ANIMATED_AVAILABLE 0
#endif
```
but unfortunately this headers aren't public in `PINRemoteImage.framework`. I think you have a better connection with Pinterest team, so please ask them to make this headers `public` and animated images will works fine after updating framework too.

**Comment by hannahmbanana** [comment]
Garrett - I believe something happened around this while I was out. Do you have context on the current situation?

**Comment by garrettmoon** [comment]
I *think* this has been resolved? Can you open a new issue on Texture if not? https://github.com/texturegroup/texture/issues
