### ISSUE TITLE
ASCellNode corner radius and shadow not working properly

### ISSUE THREAD

**Issue by tungvoduc** [facebookarchive/AsyncDisplayKit#2944]
After upgrading to ASK 2.0.1 and 2.0.2, corner radius and shadow applying to ASCellNode do not work anymore. 
I have many different ASCellNode in my project and cornerRadius does not work on all of them.
For shadow, it is not draw on nodes that are either at beginning of the list or at the end of the list (ASCollectionNode).

**Comment by tungvoduc** [comment]
I just figured out that it does not work if setting background colour for ASCellNode. I found workaround by adding a backgroundNode. This can be reproduced in any examples that use ASCollectionNode.

**Comment by hannahmbanana** [comment]
Adali - Are you aware of any recent changes that may have caused these 2 regressions?

**Comment by Adlai-Holler** [comment]
@tungvoduc What is the most recent version that was working? `2.0`?

**Comment by tungvoduc** [comment]
@Adlai-Holler : It was 2.0 beta 1.

**Comment by yxztj** [comment]
@Adlai-Holler I met the same issue. The last version confirmed to be working is 2.0.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#178
