### ISSUE TITLE
[ASCollectionNode] New constrainedSizeForNodeAtIndexPath is not called on asyncDelegate as it is defined (only on layout inspector).

### ISSUE THREAD

**Issue by hannahmbanana** [facebookarchive/AsyncDisplayKit#2947]
"This definition indicates the collectionView version is deprecated, which makes sense:

- (ASSizeRange)collectionView:(ASCollectionView *)collectionView constrainedSizeForNodeAtIndexPath:(NSIndexPath *)indexPath ASDISPLAYNODE_DEPRECATED_MSG("Use ASCollectionNode's constrainedSizeForItemAtIndexPath: instead. PLEASE NOTE the very subtle method name change.");

However, although the Node version is _defined_, it is never called.  So, a delegate can't use the method.

The indirection of the layout inspector is confusing to most developers.  Also, it still uses the collectionVIEW: method naming, and is the only way to return a constrained size at this point.

Found this when working with Scott on the compatibility / adoption path and it is an issue for apps with custom cell sizing methods that exists in the view controller." --Scott

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#179
