### ISSUE TITLE
ASViewController incorrect layout when presenting another view controller with a different orientation

### ISSUE THREAD

**Issue by ryanfitz** [facebookarchive/AsyncDisplayKit#2949]
I'm running into a layout issue on the latest version 2.0.2. I have an `ASViewController`, whose top-level node is a `ASCollectionNode` is displayed in portrait orientation. When selecting an item I present a new `ASViewController`. However, the view controller being presented only supports landscape orientation. During the presentation of the landscape view controller, the top level `ASCollectionView` layout changes to that of landscape. When dismissing the landscape view controller, the collection view occasionally does not lay itself out properly again when switching back to portrait.

I tested out with a regular `UIViewController`, but still using an `ASCollectionNode`. When using the regular UIViewController I do not experience the layout issues as I do when using an `ASViewController`

I have a [sample project](https://github.com/ryanfitz/ASDKRotation) showing this issue. In the app delegate you can toggle between using either the `ASDKViewController` or the `UIKitViewController`.

### ASViewController
Layout issues, see growing cells behind yellow background color as new vc is presented.

![ASViewController](http://i.imgur.com/i2EMLjj.gif)

### UIViewController
No layout issues, layout remains untouched as new vc is presented on screen

![UIViewController](http://i.imgur.com/RL98z7K.gif)

**Comment by hannahmbanana** [comment]
Michael (or Huy if I assign too many to Michael :) - could one of you triage this?

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#180
