### ISSUE TITLE
Memory management malfunction || zoom effect [ASVideoNode]

### ISSUE THREAD

**Issue by Petrachkov** [facebookarchive/AsyncDisplayKit#2951]
Hi everybody!

I've faced a very strange issue in ASVideoNode. In a few words : from time to time a video gets zoomed for a very short period of time while starting playback. I was looking into the problem and seem to have found a possible reason.
So, the setup is following:

An ASViewController<ASTableNode> where every cell node of the table contains an ASCollectionNode of videos (1 to N). Every video has a placeholder enabled and starts playback once it gets into "user focus"(playback is handled by me). Every time a video gets off user focus it should be reset to placeholder. So I assign asset url and use "play" and "resetToPlaceholder" methods. Pretty simple, huh?

I noticed that if I replace "resetToPlaceholder" call with "pause" - i get rid off zoom effect. But! if I have a heavy screen (say 6 table cells each of them has 2-5 videos within the collection) then playback suddenly stops after some period of time. So i went further. And here are some notes: 
1) There is some kind of memory management malfunction because it stops playback completely when a number of initialized assets is more that 5. (Those 5 play, but the others don't, even though videos have been downloaded and no errors were thrown). 
2) If i use resetToPlaceholder method again - zoom effect appears for the first time on the exact same cell where it used to stop playback while using pause method.

So, any thoughts? I could prepare a test project if my description is not clear, just need some time for it. If you need the test project - let me know.

Best regards,
Sergey

P.S. - the original video, i attached some time ago in a slack channel. The zoom effect appears somewhere from 13' second.
P.P.S. - unfortunately the file seems to be too big to attach it here

https://asyncdisplaykit.slack.com/files/sergey.petrachkov/F3EEYKB5Y/clipped_video_zooming_effect.mov

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#181
