### ISSUE TITLE
[Layout Transition API] Best way to animate all the way down a subtree?

### ISSUE THREAD

**Issue by jellenbogen** [facebookarchive/AsyncDisplayKit#2956]
Hi Guys,

I'm using the layout transition api with custom transition animations, and I'm not trying to figure out the best way to animate multiple layouts. Here is what I'm trying to do.

1. I have a container node with a custom subnode
2. In the container node I call `transitionLayout` to animate any frame changes on that node
3. And at the same time I want to have the subnode animate along side that.

Alternatively, I noticed that if just animate a layout transition of the subnode, the parent node's frame doesn't animate at the same time. So if the size of the subnode changes as a result of the relayout its getting clipped by the parent node, since it hasn't grown with the subnode.

Thoughts?

**Comment by garrettmoon** [comment]
Sorry that we never replied to you :( If you're still having issues, consider asking the question on our slack channel: http://texturegroup.org/slack.html
