### ISSUE TITLE
Transactional Layout System

### ISSUE THREAD

**Issue by garrettmoon** [facebookarchive/AsyncDisplayKit#2977]
Making our layout system transactional will aid in several other goals we have.

**Comment by maicki** [comment]
Related #2407

**Comment by Adlai-Holler** [comment]
@master-nevi Moved discussion of #2407 over to here

**Comment by master-nevi** [comment]
Also related: https://github.com/facebook/AsyncDisplayKit/issues/1400

https://productpains.com/post/asyncdisplaykit/support-for-simultaneous-layout-transitions

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#184
