### ISSUE TITLE
Support interactive transitions

### ISSUE THREAD

**Issue by garrettmoon** [facebookarchive/AsyncDisplayKit#2978]
We'd like to add support for transitioning an arbitrary percentage between two layout elements. This will allow us to attach gestures to drive the percentage and have interactive transitions.

**Comment by garrettmoon** [comment]
Related to #2804

**Comment by appleguy** [comment]
@garrettmoon @maicki this is a very exciting feature! I would love to be an early tester of this, or to give feedback on API design in the context of some use cases I have in mind.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#185
