### ISSUE TITLE
Improve collection datasource performance

### ISSUE THREAD

**Issue by garrettmoon** [facebookarchive/AsyncDisplayKit#2979]
We do not currently take advantage of collections or views that use objects of the same size. Would provide performance benefits to objects like Profile, Topics, etc that leverage this pattern heavily.

**Comment by nguyenhuy** [comment]
More details discussed here: https://github.com/facebook/AsyncDisplayKit/issues/3219

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#186
