### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by WiesnerPeti** [facebookarchive/AsyncDisplayKit#2996]
Hi guys,

I tried to google this, also searched the FAQ section, but I could not find the answer for the question above. In the FAQ it is clearly stated that the library [does not support AutoLayout](http://asyncdisplaykit.org/docs/faq.html#asyncdisplaykit-does-not-support-uikit-auto-layout-or-interfacebuilder) (that supports RTL automatically), does that mean, that there is now way to switch to RTL mode , let's say in a layout spec?

I tried to test a sample project with RTL turned ON and all the texts are mirrored, but the layout is not.

Thank you very much for the answer in advance! :)

**Comment by garrettmoon** [comment]
Hey @WiesnerPeti RTL isn't something we support yet, but we definitely think it would be an awesome feature of layout specs! We'd gladly accept pull requests supporting this goal.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#189
