### ISSUE TITLE
Strange ASCellNode background in 2.1

### ISSUE THREAD

**Issue by acedened** [facebookarchive/AsyncDisplayKit#3044]
ASCellNode in 2.1 has strange background in addition to the one that I have specified in code. This background doesn't respond to frame or cornerRadius changes. Everything was fine in 2.0.1.

Here is the screenshot of 2.1:
![wrong](https://cloud.githubusercontent.com/assets/7037300/23075081/3a552fa8-f54c-11e6-9ee5-18db6e8eb745.png)

This is how it was in 2.0.1:
![fine](https://cloud.githubusercontent.com/assets/7037300/23075131/662ad006-f54c-11e6-9cd1-dd5623e7b553.png)

**Comment by maicki** [comment]
This can be related to: #3053

**Comment by garrettmoon** [comment]
It looks like this was fixed, if not, do you mind reopening an issue on the Texture repo? https://github.com/texturegroup/texture/issues
