### ISSUE TITLE
RFC: Deprecate -[ASDisplaynode calculatedSize]

### ISSUE THREAD

**Issue by maicki** [facebookarchive/AsyncDisplayKit#3050]
After talking with Adlai, there are a couple of reasons, we should think of deprecating `calculatedSize` sooner than later so users can move away from using this method.

Some reasons:
- The return value of `calculatedSize` relies on the fact (and side effect) that `layoutThatFits:` or a layout pass happened before.
- Furthermore the return value of this method can differ between a layout that was applied in a recent layout pass and a pending layout that was created by calling `layoutThatFits:`. By default it returns the value of the prepared layout if a prepared layout exists. This is obviously wrong, but for backwards compatibility we had to do it this way.
- In the future there will be no way anymore to access this kind of size that relies on some side effect which happened before. We will likely introduce a method to returns the size like `sizeThatFits:` which will be called without having to have any side effect before.

For a smoother transition at the moment we should recommend to get the currently calculated size the following way:

```Objc
ASSizeRange *constrainedSize = [self constrainedSizeForCalculatedLayout];
ASLayout *layout = [self layoutThatFits:constrainedSize];
CGSize calculatedSize = layout.size;
```

**Comment by appleguy** [comment]
@maicki great summary of the current situation.  This was a tricky and sad thing to discover when you were creating the modern 2.0 layout API.  I agree 100% with deprecating this method!

I do think there should be at least one major release where the method remains implemented, but internally just uses the workaround you wrote (constrainedSizeForCalculatedLayout, layoutThatFits, layout.size).  After users have a short period to make the changes, then it could be removed entirely.

This suggestion is based on seeing a rapid pace of users still upgrading from 1.x to 2.x; I'm helping folks with the process at least a couple times a week.  It's a huge incentive for people to upgrade when they can stabilize their app on the new version first, and then fix all the deprecations in a separate pass.  Congrats to the team on achieving such a seamless upgrade for a major framework!!!  Remember AFNetworks' breaking updates that people could never get past? :-P

**Comment by maicki** [comment]
@appleguy Totally agree! We would slowly deprecate it.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#193
