### ISSUE TITLE
setASDKCollectionNode not found Swift 3

### ISSUE THREAD

**Issue by bevbomb** [facebookarchive/AsyncDisplayKit#3051]
I'm unable to access the collection node setter function for IGListAdapter in Swift.
I'm currently using cocoapods and pulling directly from master branch. When ever i try to use the setter function it returns not found.

**Comment by MarvinNazari** [comment]
@bevbomb you need to use the subspec `pod 'AsyncDisplayKit/IGListKit'` and you can find a sample project here #3047

**Comment by maicki** [comment]
Thanks @MarvinNazari for helping out.

@bevbomb I will close this issue for now as it seems you got the right direction. Please reopen if you don't think so.  Thanks!

**Comment by QuynhNguyen** [comment]
@maicki This is still broken for Carthage user

**Comment by maicki** [comment]
@QuynhNguyen You mind adding a small example project to this issue. Thanks!

**Comment by garrettmoon** [comment]
Going to close this out since there's been no reply with a sample project.
