### ISSUE TITLE
ASRelativeLayoutSpecPositionNone behaves differently than Start, mention in Upgrade to 2.0 docs

### ISSUE THREAD

**Issue by skensell** [facebookarchive/AsyncDisplayKit#3055]
Hey Guys, I'm in the process of upgrading from 1.9 to 2.1. This isn't necessarily a bug report, rather just a layout API change which I think needs better documentation.

I am frequently overlaying nodes with `ASOverlayLayoutSpec`s containing `ASRelativeLayoutSpec`s. In 1.9, here's how I would construct an `ASRelativeLayoutSpec`.
```Obj-C
    ASStackLayoutSpec* bottomMatterStack = [ASStackLayoutSpec horizontalStackLayoutSpec];
    bottomMatterStack.alignItems = ASStackLayoutAlignItemsStart;
    bottomMatterStack.justifyContent = ASStackLayoutJustifyContentSpaceBetween;
    bottomMatterStack.children = @[_skipButton, _nextButton];
    
    ASInsetLayoutSpec* bottomMatterInset  = [bottomMatterStack mx_inset:UIEdgeInsetsMake(0, 20, 20, 20)];
    
    ASRelativeLayoutSpec* bottomMatterRelative = [ASRelativeLayoutSpec relativePositionLayoutSpecWithHorizontalPosition:ASRelativeLayoutSpecPositionStart verticalPosition:ASRelativeLayoutSpecPositionEnd sizingOption:ASRelativeLayoutSpecSizingOptionMinimumHeight child:bottomMatterInset];
```
producing
<img width="317" alt="screen shot 2017-02-21 at 10 26 57 am" src="https://cloud.githubusercontent.com/assets/3983827/23158726/835a797a-f820-11e6-8577-f0dd4d4059a0.png">
In 2.1, however, it renders like so
<img width="316" alt="screen shot 2017-02-21 at 10 28 09 am" src="https://cloud.githubusercontent.com/assets/3983827/23158727/84012b80-f820-11e6-80be-11698a0af756.png">
The fix is to change `ASRelativeLayoutSpecPositionStart` to `ASRelativeLayoutSpecPositionNone`.

Another random, unrelated complaint (but not a huge deal): `ASPagerNodeDataSource/Delegate` silently changed
```Obj-C
// old
- (ASSizeRange)pagerNode:(ASPagerNode *)pagerNode constrainedSizeForNodeAtIndexPath:(NSIndexPath*)indexPath
// new
- (ASSizeRange)pagerNode:(ASPagerNode *)pagerNode constrainedSizeForNodeAtIndex:(NSInteger)index
```

**Comment by maicki** [comment]
@skensell Hey, yeah the behavior of `ASRelativeLayoutSpec` changed a bit in this cases in 2.0 and I'm sorry we didn't document that thoughtfully.

We would appreciate if you put up a PR for the documentation to update it to reflect this behavior. Thanks!

**Comment by garrettmoon** [comment]
Going to close this out, please feel free to open a PR to improve documentation!
