### ISSUE TITLE
Batch fetch not called in ASPagerNode with auto scroll and manual scroll.

### ISSUE THREAD

**Issue by jaichaudhry** [facebookarchive/AsyncDisplayKit#3056]
I am using ASPagerNode with infinite scrolling, the problem occurs when I scroll my pagerNode towards left which sets _deceleratingVelocity in scrollViewWillEndDragging: with positive x. After that I use scrollToItemAtIndex: to move towards right.
The problem is _deceleratingVelocity would not change now as scrollViewWillEndDragging would not be called when I use scrollToItemAtIndex: and due to positive x the scrollDirection would always be left and hence _checkForBatchFetching would always return false.
I figured that setting _deceleratingVelocity as CGPointZero in scrollToItemAtIndexPath: would fix the issue. 
Let me know if that's a correct solution. I can create a PR then

**Comment by nguyenhuy** [comment]
Thanks for reporting this. @Adlai-Holler has much better understanding behind the flags in `_checkForBatchFetching` and thus can decide if yours is a correct solution.

**Comment by Adlai-Holler** [comment]
@jaichaudhry Good points, thanks for reporting! We can definitely improve our scroll view state tracking here.

I wonder if a more direct solution would be to add:

```objc
- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView
{
  _deceleratingVelocity = CGPointZero;
}
```

Does that fix your use case?

In the future, we should probably replace `_deceleratingVelocity: CGPoint` with `_animatingDirection: ASScrollDirection` and then we can set that in `scrollToItemAtIndexPath:`, `willEndDragging:` and many other methods.

**Comment by jaichaudhry** [comment]
@Adlai-Holler Yes that should solve the issue of batch fetch not getting called since the _deceleratingVelocity would be reset in scrollViewDidEndDecelerating:

**Comment by garrettmoon** [comment]
Going to close this out since it's community debugging and hasn't been commented on in a while.
