### ISSUE TITLE
[ASEditableTextNode] maximumLinestoDisplay does not consider textContainerInset

### ISSUE THREAD

**Issue by skensell** [facebookarchive/AsyncDisplayKit#3065]
The feature implemented to solve this issue
https://github.com/facebook/AsyncDisplayKit/issues/2777
resolved with this PR:
https://github.com/facebook/AsyncDisplayKit/pull/2867
is great and a very useful feature.  However it doesn't work if I set the `textContainerInset` property.

For example, try `_textInputNode.textContainerInset = UIEdgeInsetsMake(4, 15, 4, 15);` and you will see that it doesn't expand even when there is one line of text + <30pts of new text.

**Comment by skensell** [comment]
As an additional feature request, it would be nice if this property `maximumLinesToDisplay` was a `CGFloat` so that you can show a portion of the next line which gets cut off. It would help the user know they can scroll down.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#194
