### ISSUE TITLE
ASScrollNode examples

### ISSUE THREAD

**Issue by rlegcleg** [facebookarchive/AsyncDisplayKit#3106]
Hello.
I am developing an iOS App based on AsyncDisplayKit. And I used the ASScrollNode to display some interfaces, but they can not been scrolled. And I can not find any example projects about it. I think the ASScrollNode‘s documents lack detail. 
Would you like to add to information or examples about the ASScrollNode

**Comment by Kuluum** [comment]
@rlegcleg the main trick on latest versions is to set 
_scrollNode.automaticallyManagesContentSize = YES;

If it doesn't works for you, try to make some experiments with layout spec of scroll node inners and parent spec of scroll node (spec that scroll node is in).

http://pastebin.com/tRErPK5p

This is the trivial sample of scroll node usage, but, to tell the truth, I have a lot of trubbles with using scroll node with layout that more complex that one text node =).

Also you can see https://github.com/facebook/AsyncDisplayKit/issues/780 discussing, it helps in past.

**Comment by garrettmoon** [comment]
Going to close this out for now as there hasn't been activity recently.
