### ISSUE TITLE
Memory issue When repeatly enter the same ASDK view

### ISSUE THREAD

**Issue by IvanChan** [facebookarchive/AsyncDisplayKit#3111]
I use asdk to layout news insteads of using webview.
The news-view may looks like Apple News App, layout images, texts etc. 
![aa](https://cloud.githubusercontent.com/assets/3829585/23452642/fe402c40-fe9f-11e6-8617-b61517f487f8.png)

**The memory keep growing when I repeatly enter this same view! about 10M-memory-grow every time.**

![b](https://cloud.githubusercontent.com/assets/3829585/23452457/51978e52-fe9f-11e6-9ee2-bed4995db8a1.png)
![c](https://cloud.githubusercontent.com/assets/3829585/23452460/539a1f80-fe9f-11e6-912f-252245c2c41d.png)

Even thougth a lot of image is being rendered, but I quit this view, make sure the dealloc is called. the memory still there! 
Memory warning is useless too.

**Comment by garrettmoon** [comment]
@IvanChan Hmm, can you create a sample project? We're not seeing similar issues in Pinterest. Is it possible there's a retain cycle in your code?

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#198
