### ISSUE TITLE
[ASBatchFetching] Suggestions / improvements for edge cases where batch fetch is called repeatedly

### ISSUE THREAD

**Issue by flovouin** [facebookarchive/AsyncDisplayKit#3127]
Hi guys,

Following a Slack message, I'm posting this issue about some (probably unwanted) extra calls to `willBeginBatchFetch`.
I noticed two cases in which I get lots of calls to my delegate (basically on every `scrollViewDidScroll` event, minus the time I actually need to perform the call to a remote service):

- When trying to scroll up at the top of a collection (hence triggering the bounce effect), but only if the `contentLength` doesn't fill the required number of leading screens. In this case, when the user ends dragging, the bounce effect makes the content go down, hence `isScrollingTowardHead = NO` and `remainingDistance <= triggerDistance`, which triggers the batch fetch. This only happens when bouncing at the top of the collection, because when bouncing at the bottom, `isScrollingTowardHead = YES` during the animation.
- When bouncing (at the top **and** bottom of the collection), when `hasSmallContent = YES`. During the animation, `scollViewDidScroll` is called repeatedly and the check for small content makes an early `return YES`. Bouncing is actually possible when `hasSmallContent = YES` if the `contentInset` for the scroll view is positive in the scroll direction.

I haven't thought in depth about how to solve this, but a few ideas include:
- Taking into account the `contentInset` in the logic.
- Using the view's current `contentOffset` to determine if there's currently a bounce animation going on.

Now, one could argue that these two cases don't happen once the batch fetch is completed because it's supposed to add new elements to the collection. Adding new elements to the collection should therefore make `remainingDistance > triggerDistance` and `hasSmallContent = NO` at some point. But in my case the remote data source doesn't have any other object to return. However, I cannot say that batch fetches should no longer happen using `shouldBatchFetch` because the data source might change in the future and I still want to check periodically. I personally think the batch fetch mechanism allows me to do just that, but one could argue that this is a different behaviour.

I think it's still worth investigating, but tell me what you guys think! :-)

Cheers,
Flo

**Comment by Adlai-Holler** [comment]
Good points! `shouldBatchFetch:` may need better documentation – it doesn't mean "never ask me about batch fetching again" it just means "I don't want to batch fetch right now." In effect, that method `shouldBatchFetch` is meant to be called every frame, if the current content isn't enough, and ASDK expects the logic in that method to be pretty fast.

**Comment by flovouin** [comment]
Thanks for your reply @Adlai-Holler !

Yes sorry about that, I didn't make myself clear but I figured that `shouldBatchFetch` would be called every time. What I meant is that I have no real way of knowing whether new items are available, except by making a call to the remote service. And apart from these inconvenient edge cases, the existing batch fetching logic seems to be the way to do just that, and suits my needs perfectly. In the general case, when the user scrolls down, a new batch fetch is triggered only once (if needed), I make the call to the remote service (which may or may not return new items), and voila !

Now concerning the two edge cases, do you think it is the developper's responsibility to take care of this in `shouldBatchFetch` or could the logic in `ASBatchFetching` be changed?
- A solution to avoid spamming the remote service would be to ensure a delay between calls. This might be needed anyway depending on the application, and it is clearly the developper's job to implement that.
- However a complementary solution would be to check whether the batch fetch was triggered during a bounce animation (and disable the repeated calls). This implies checking `contentInset` and `contentOffset` of the scroll view. It would seem that this would be more adequate inside `ASBatchFetching`, and in my opinion would be a legitimate improvement. :-)

**Comment by flovouin** [comment]
Hey guys,

So currently I've simply solved the problem by adding the following logic to `shouldBatchFetch`:

```
func shouldBatchFetch(for collectionNode: ASCollectionNode) -> Bool {
    let isScrollingUp = collectionNode.view.scrollDirection.contains(.up)
    let isBouncingAtTop = -collectionNode.view.contentOffset.y > collectionNode.view.contentInset.top
    return !isScrollingUp && !isBouncingAtTop
}
```

- `isScrollingUp` is necessary even though the check already exists in the current `ASDisplayShouldFetchBatchForContext` implementation because it is bypassed when `hasSmallContent` is `YES` (the second case of my original issue). This could simply be solved by moving the `isScrollingTowardHead` check above the small content check.
- `isBouncingAtTop` is also pretty much self-explanatory and solves the first case of the original issue. This could be added to ASDK's logic, although the `contentInset` should be forwarded to `ASDisplayShouldFetchBatchForContext`.

It shouldn't be too hard to add this in `ASDisplayShouldFetchBatchForContext`, and I feel that it would be at its place in the batch fetching logic. What do you guys ( @appleguy @Adlai-Holler @maicki ) think? Is this PR-worthy? I don't mind taking care of it if you think it is, just didn't want to work on it before asking you first.

Thanks,

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#199
