### ISSUE TITLE
set the lineSpacing of the ASTextNode seems not correct?

### ISSUE THREAD

**Issue by abellee** [facebookarchive/AsyncDisplayKit#3174]
multi-line text in ASTextNode, and set the paragraph style's lineSpacing to 5 or more,
and set the backgroundColor of the ASTextNode, that let me know the edges of the text clearly.
then I found the first line just equal to the left and top, but the last line is not,
seems like there is more than one line height white space, at the bottom of the last line.
is this a problem? or any settings I have missed?

**Comment by Kaspik** [comment]
Probably the same issue as already tracked here: https://github.com/facebook/AsyncDisplayKit/issues/3128

**Comment by abellee** [comment]
@Kaspik so it is a bug?
now I only have to set `lineHeightMultiple` instead of `lineSpacing` to avoid this problem

**Comment by Kaspik** [comment]
Yes, this is a bug.

**Comment by Shafichariri** [comment]
Hello Guys, did you find a work-around? Using 'lineHeightMultiple' fixes this problem but it creates another [Extra top spacing].

**Comment by maicki** [comment]
@abellee Can you please try setting  `truncationMode = NSLineBreakByTruncatingTail` and test again. Thanks!

**Comment by garrettmoon** [comment]
Going to close this out since there's been no reply.
