### ISSUE TITLE
UIViewController.viewDidAppear has not called in first ASCellNode 

### ISSUE THREAD

**Issue by muukii** [facebookarchive/AsyncDisplayKit#3183]
I added UIViewController to ASCellNode in ASPagerNode.
But, first UIViewController.viewDidAppear has not called.
When scroll, next and previous UIViewController.viewDidAppear has called.

I think should call `beginAppearanceTransition` and `endAppearanceTransition` at suitable timing inside ASCellNode

What do you think?

**Comment by xiaozao2008** [comment]
Same problem on me.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#202
