### ISSUE TITLE
[RFC] Bazel support

### ISSUE THREAD

**Issue by nguyenhuy** [facebookarchive/AsyncDisplayKit#3184]
With recent internal developments around build tools, we'll need Bazel support for ASDK in the next few months.  The first step is to be able to build ASDK-Core and tests.  Then it'll be nice to eventually build PINRemoteImage and PINCache, and sample projects.  Finally, by the end of this year, hopefully we'll have a Bazel CI and HTTP cache that should boost our build time quite significantly.

Buck support, sadly, has seen limited usage but I hope it'll not be the case for Bazel support.  We can keep Buck support for now and remove it when it becomes a burden to maintain.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#203
