### ISSUE TITLE
Support modifying a node tree on a background thread on a loaded node

### ISSUE THREAD

**Issue by maicki** [facebookarchive/AsyncDisplayKit#3185]
There are more and more use cases where we would like to modify the node tree on a background thread. One is a FIXME we have in `ASDisplayNode` if a node is in the loading process:

// FIXME: Ideally we'd call this as soon as the node receives -setNeedsLayout but automatic subnode management would require us to modify the node tree in the background on a loaded node, which isn't currently supported.

As we have more FIXME like that we should consider fixing the FIXMEs and add support for it.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#204
