### ISSUE TITLE
[RFC] ASVideoNode should not subclassing ASNetworkImageNode

### ISSUE THREAD

**Issue by maicki** [facebookarchive/AsyncDisplayKit#3199]
Currently `ASVideoNode` is subclassing `ASNetworkImageNode`.

This has a couple of downsides e.g.:
- Locking is very difficult due to the nature of subclassing `ASImageNode` / `ASNetworkImage`
- There is no way to use a different placeholder node as `ASNetworkImageNode`
- We should be in favor of composition over inheritance

Therefore we should move `ASVideoNode` to a thin wrapper around `AVPlayer` and be a subclass of `ASDisplayNode`.

If we would like support placeholder we should create a separate node that combines an `ASVideoNode` and another node that will be the placeholder.

**Comment by nguyenhuy** [comment]
I totally support this.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#205
