### ISSUE TITLE
App crashes due to assertion "Expected that all old sections were deleted before...sections.."

### ISSUE THREAD

**Issue by Rokimkar** [facebookarchive/AsyncDisplayKit#3201]
I have a ASTableNode and the ASCellNode contains a horizontal ASCollectionNode in it with a default 10 items. Everything works fine when the ViewController containing this ASTableNode is pushed in the Navigation.
But, as soon as I pop the ViewController it crashes with an assertion.

It happens for AsyncDisplayKit pod 2.2 version.
It is working absolutely fine on the previous pod version.

P.S. It got crashed at " **ASDisplayNodeAssert([self editingNodesOfKind:ASDataControllerRowNodeKind].count == 0, @"Expected that all old sections were deleted before %@. Sections: %@", NSStringFromSelector(_cmd), [self editingNodesOfKind:ASDataControllerRowNodeKind]);**" in **ASCollectionDataController.mm**.

**Comment by naveen7b** [comment]
**+1**
Same issue occurred to me with version 2.2

**Comment by hamewang** [comment]
Can not use    UICollectionViewFlowLayout ->estimatedItemSize

**Comment by Adlai-Holler** [comment]
@Rokimkar Could you provide some sample code with a repro? Are you using `estimatedItemSize` as @hamewang mentioned?

**Comment by hamewang** [comment]
@Adlai-Holler create viewController extens ASViewController， overwrite  init Method
- (instancetype)init {
    UICollectionViewFlowLayout *fLayout = [[UICollectionViewFlowLayout alloc] init];
    fLayout.minimumLineSpacing = 10;
    fLayout.minimumInteritemSpacing = 10;
    fLayout.estimatedItemSize = CGSizeMake(100, 50);
    ASCollectionNode *mainNode = [[ASCollectionNode alloc] initWithCollectionViewLayout:fLayout];
    if (self = [super initWithNode:mainNode]) {
        mainNode.dataSource = self;
        mainNode.delegate = self;
    }
    return self;
}

ASCollectionDataSource Method

- (ASCellNodeBlock)collectionNode:(ASCollectionNode *)collectionNode nodeBlockForItemAtIndexPath:(NSIndexPath *)indexPath {
    return ^ASCellNode *() {
        ASTextCellNode *nodel = [[ASTextCellNode alloc] init];
        nodel.text = @"aaaa";
        return nodel;
    };
}

 self.navigationController pushViewController   this method is OK;
but  self.navigationController popViewControllerAnimated this method error

**Comment by Rokimkar** [comment]
@Adlai-Holler  [https://github.com/naveen7b/AsyncDisplayKit-Example](link) for the example project. This project will work fine if the Async display kit version is before 2.2. Thanks @naveen7b  for the sample code.

**Comment by zjmdp** [comment]
I got the same issue rarely, but it did happen.

**Comment by yxztj** [comment]
Same here. Guess the app didn't crash in production due to NSAssert being disabled in release build.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#206
