### ISSUE TITLE
[Sample Projects] CocoaPods Error about Prerelease PINRemoteImage

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#3212]
If you run `pod install` on most of our examples, you get this error:

```
[!] Due to the previous naïve CocoaPods resolver, you were using a pre-release version
of `PINRemoteImage/iOS`, without explicitly asking for a pre-release version, which
now leads to a conflict. Please decide to either use that pre-release version by adding
the version requirement to your Podfile (e.g. `pod 'PINRemoteImage/iOS', '= 3.0.0-beta.2'`)
or revert to a stable version by running `pod update PINRemoteImage/iOS`.
```

This is really irritating.
- The `Podfile` doesn't specify the `PINRemoteImage/iOS` dependency. It's specified in `AsyncDisplayKit.podspec`.
- Our podspec specifically requests the pre-release version of PINRemoteImage.
- So I believe that running `pod update PINRemoteImage/iOS` in each example once will save this from being a problem in the future, but I'm not sure.
- There is no `Podfile.lock` checked in for the examples, so I'm not sure how CocoaPods is determining that we were using a naïve previous resolver.

Thoughts @maicki @nguyenhuy ?

**Comment by nguyenhuy** [comment]
IIRC, I ran into this problem before and `pod update` helped. 

> There is no Podfile.lock checked in for the examples, so I'm not sure how CocoaPods is determining that we were using a naïve previous resolver.

I think it looks at your local Podfile.lock. I'd vote for checking those files into our repo.

**Comment by nguyenhuy** [comment]
https://github.com/pinterest/PINRemoteImage/issues/335 is probably the same problem.

**Comment by master-nevi** [comment]
Those Pinterest pods have been in beta for a loooong time; a pod in beta for that long and in production apps like Pinterest is probably production ready at this point isn't it?

**Comment by nguyenhuy** [comment]
@garrettmoon ^

**Comment by garrettmoon** [comment]
@master-nevi yeaaaaah, we just haven't gotten around to do a proper release.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#207
