### ISSUE TITLE
The example `ASRatioLayoutSpec` in the sample Project `AsyncDisplayKitOverview` cannot work as expected

### ISSUE THREAD

**Issue by xilin** [facebookarchive/AsyncDisplayKit#3216]
The sample is located in [here](https://github.com/facebook/AsyncDisplayKit/blob/master/examples/AsyncDisplayKitOverview/Sample/OverviewComponentsViewController.m#L365).

It seems that the `constrainedSize` is fixed as `{min : {100, 100}, max: {100, 100}}` so that the  `ASRatioLayoutSpec` layout cannot produce correct result.

**Comment by nguyenhuy** [comment]
The fixed constrainedSize is for `parentNode`, and the ratio spec is applied for the `childNode` of that node. I'd imagine the childNode has a size of `{100, 25}`, no?

**Comment by xilin** [comment]
Nope. The childNode is in blue color and see the snapshot

![simulator screen shot 29 mar 2017 11 59 47 pm](https://cloud.githubusercontent.com/assets/543395/24464240/cddba4ba-14db-11e7-945b-5edd88b8bcbe.png)

**Comment by nguyenhuy** [comment]
Oh yeah, you're entirely right. The ratio spec got a fixed size range of `{100, 100}`! We should fix that!

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#208
