### ISSUE TITLE
[RFC] Ending Support for Using "Naked" ASCollectionView

### ISSUE THREAD

**Issue by Adlai-Holler** [facebookarchive/AsyncDisplayKit#3227]
This is pretty severely limiting our development of ASCollectionNode as @nguyenhuy points out in #3219.

The initializers for those classes have been deprecated since the 2.0 betas, and the migration pathway to use ASCollectionNode is not very difficult, so I advocate for dropping support soon, maybe in the next major point release.

Comments @nguyenhuy @maicki @ay8s @appleguy @lappp9 @garrettmoon

**Comment by nguyenhuy** [comment]
Thanks for bringing this up, @Adlai-Holler.

I'd vote for dropping support in the next major release. We also should have a clear guideline/rule on how long deprecated APIs are supported.

**Comment by ay8s** [comment]
👍  Agree with @nguyenhuy for next major release & outlining the timeline on deprecations will help it not being a surprise for future releases.

**Comment by lappp9** [comment]
Yep, totally agree, migrating is pretty straightforward so seems reasonable to me.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#210
