### ISSUE TITLE
The cell in ASTableNode, ASCollectionNode never dealloc, when number of cells increase, the memory increases all the time.

### ISSUE THREAD

**Issue by evanxie-cn** [facebookarchive/AsyncDisplayKit#3231]
Firstly, thank you very much for creating such amazing framework, it's really so smooth, so fluent. 

When I use ASTableNode/ASCollectionNode, I encountered a memory issue, with the new cell creating, the memory cost will be higher and higher, finally **crash the app**.

I uses the Facebook official **CatDealsCollectionView** sample to test the  **ASTableNode ASCollectionNode** memory issue. Finally I found the cells are never dealloc, eg. we have 10,000 cells, ASTableNode will create 10,000 cells, and these cells are both in memory. 

When you scroll down the cells, the memory will increase a little by a little. If you scroll down and down, the memory cost will reach up several hundred, even over 1 GB, then crash.

When you scroll down to several thousands cells, then let the iPhone rotate to landscape, the whole table node will block for several seconds, then layout finished, it recovered, then scroll down again, it is still smooth.  

But when memory cost 1.3GB, the app crashed. 

[CatDealsCollectionView.zip](https://github.com/facebook/AsyncDisplayKit/files/881339/CatDealsCollectionView.zip)
![img_0133](https://cloud.githubusercontent.com/assets/16699438/24492544/719784fc-155e-11e7-9d3e-92642b39bea3.JPG)

https://github.com/evanxie-cn/AsyncDisplayKit/blob/master/MemoryCrash.MOV

**Comment by Ruanjijian** [comment]
+1
Same issue occurred to me with version 2.1 
All Heap & Anonymous VM Have been increasing

**Comment by evanxie-cn** [comment]
I tested on the SDK 2.1, and 2.2, both have this issue.

**Comment by Adlai-Holler** [comment]
@appleguy I know you are crazy busy but I think you're the man to investigate this very serious issue, as the rest of the team is heads-down on other tasks.

@maicki investigated and he found that CoreGraphics is caching CGImages for layer contents without us asking for it to. We need to prevent this behavior!

**Comment by evanxie-cn** [comment]
@Adlai-Holler Thanks for your explanation and team hard work. So, maybe we just wait for this issue resolved, right?

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#211
