### ISSUE TITLE
[RFC] Fluent interface for layout code

### ISSUE THREAD

**Issue by cesteban** [facebookarchive/AsyncDisplayKit#3238]
I've been using AsyncDisplayKit for a while. It is a beautifully designed API, thanks a lot for your work. However, I've been missing a more visual interface for defining layouts. I created a bunch of categories over `ASDisplayNode` and `ASLayoutElement` that make it possible to write layout code using a fluent API. So for example the layout of `PhotoTableNodeCell` in [ASDKgram-Swift](https://github.com/facebook/AsyncDisplayKit/blob/master/examples_extra/ASDKgram-Swift/ASDKgram-Swift/PhotoTableNodeCell.swift) example can be translated to this:

```swift
override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
  return ASStackLayoutSpec
    .vertical()
    .withChildren([
      ASStackLayoutSpec()
        .withAlignItems(.center)
        .withChildren([
          avatarImageNode
            .withPreferredSize(avatarImageNodePreferredSize)
            .withInset(Constants.CellLayout.InsetForAvatar),
          usernameLabel
            .withFlexShrink(1),
          ASLayoutSpec.spacer(),
          timeIntervalLabel
            .withSpacingBefore(Constants.CellLayout.HorizontalBuffer)
          ])
        .withInset(Constants.CellLayout.InsetForHeader),

      photoImageNode.withRatio(1),

      ASStackLayoutSpec
        .vertical()
        .withSpacing(Constants.CellLayout.VerticalBuffer)
        .withChildren([
          photoLikesLabel,
          photoDescriptionLabel])
        .withInset(Constants.CellLayout.InsetForFooter)
      ])
}
```

This layout reads from top to bottom without interruptions. The outermost code define the general structure, and inner parts define the details, so less visual scanning needed. Also, it is much faster to add, remove, and reorganize specs. Finally, note that modifications of `style` properties are also **composable** with layout specs (see usages of `withPreferredSize` or `withFlexShrink` inline with layout specs definition). This avoids interruptions on how the code visually flows.

To me this is has been a great improvement in the way I write ASDK layout code. However, I would like to know whether this type of API fits the vision you have for how AsyncDisplayKit should be used. I'm relative newcomer to ASDK, so perhaps I'm walking in the wrong direction?

If there is interest in this categories I can brush them up and send a PR or perhaps distribute them as a separated component.

**Comment by cesteban** [comment]
In case it helps, I've created a public repo with these categories as they are now, and a brief README explaining the fluent API:

https://github.com/cesteban/ASDKFluentExtensions

It is not finished work, but it should be enough to transmit the idea. Any feedback would be very much appreciated.

Thanks!

**Comment by MarvinNazari** [comment]
@Adlai-Holler made this too
https://github.com/Adlai-Holler/AsyncDisplayKitExtensions/blob/master/AsyncDisplayKitExtensions/Layout.swift
It's not updated though.

**Comment by cesteban** [comment]
I didn't know about these extensions by @Adlai-Holler! It is the same concept, and even the syntax is almost identical. I was looking for feedback, so this is great, thanks a lot @MarvinNazari.

The implementation looks very similar to my [first attempt](https://gist.github.com/cesteban/e5d265989ed319c0f83bfda3bffdcf8c) on this. Extending `ASLayoutElement` is much better because there is no code duplication. However protocol extension won't be visible from ObjC, so I abandoned that approach in favour of an ObjC implementation.

**Comment by MarvinNazari** [comment]
@cesteban yeah your extension would really help me, much nicer to work with these APIs.

**Comment by cesteban** [comment]
That's great to know @MarvinNazari! I will create a public pod to make things easier. Any further comments you have please let me know.

**Comment by garrettmoon** [comment]
@cesteban this is really neat and makes things far more readable. I really want @nguyenhuy and @maicki to weigh in as they're the layout experts.

**Comment by cesteban** [comment]
Thanks a lot @garrettmoon. Please let me know if I can do something in the meanwhile. I would be happy to help pushing this forward.

**Comment by maicki** [comment]
@cesteban Hey, I like the idea and as you can see in the `ASDKGram` example I tried to design the current API with that in mind.

That said I don't think we should add this to the core framework though, but we would be very happy if you could bootstrap that in a separate repo / component and we can link to it and if other developer would like to use it can just add it via Cocoapods, Carthage etc. 

Thoughts?

**Comment by nguyenhuy** [comment]
@cesteban First of all, thanks for sharing this awesome proposal!  I like the syntax quite a lot.

However, having yet another way to construct layouts will be confusing to new folks and make it hard to maintain the documentation.  Unless there is an overwhelming demand and support for this new syntax, we might not want to merge it to the core framework.  And even if we do, it will need to replace the existing API which requires careful planning.  The replacement deserves a major release on its own and with it updates in the documentation, examples, etc

For the time being, would you like us to help promote your work, @cesteban?  We can have a page dedicated to 3rd-party extensions/integrations.  IMHO, we can even host your repo under TextureGroup org (only if you want and with you being the primary author of course!).

**Comment by cesteban** [comment]
@maicki @nguyenhuy Thank you very much for your responses. I agree: Let's distribute this as a separated component and see if it gets some traction.

It would be great if you help promoting these extensions though. I would be happy as well having the repo under TextureGroup, if you think that's ok. I'm not specially worried about authorship, I just want this to be more widespread. It's been very useful to me when writing Texture layout code, but it doesn't make much sense if I'm the only one using it 😅

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#213
