### ISSUE TITLE
Crash on _deleteNodesAtIndexPaths:withAnimationOptions

### ISSUE THREAD

**Issue by gralexey** [facebookarchive/AsyncDisplayKit#3247]
Hi, have such problem:

Fatal Exception: NSRangeException
*** -[NSMutableArray removeObjectsAtIndexes:]: index 50 in index set beyond bounds [0 .. 49]
Fatal Exception: NSRangeException
0  CoreFoundation                 0x18b11efd8 __exceptionPreprocess
1  libobjc.A.dylib                0x189b80538 objc_exception_throw
2  CoreFoundation                 0x18b07297c CFBundleCopyResourceURLsOfType
3  AsyncDisplayKit                0x100ac6b48 __ASDeleteElementsInMultidimensionalArrayAtIndexPaths_block_invoke (ASMultidimensionalArrayUtils.mm:146)
4  AsyncDisplayKit                0x100ac6800 ASRecursivelyUpdateMultidimensionalArrayAtIndexPaths(NSMutableArray*, NSArray const*, unsigned long&, NSIndexPath*, unsigned long, void (NSMutableArray*, NSIndexSet*, unsigned long) block_pointer) (ASMultidimensionalArrayUtils.mm:47)
5  AsyncDisplayKit                0x100ac6650 ASRecursivelyUpdateMultidimensionalArrayAtIndexPaths(NSMutableArray*, NSArray const*, unsigned long&, NSIndexPath*, unsigned long, void (NSMutableArray*, NSIndexSet*, unsigned long) block_pointer) (ASMultidimensionalArrayUtils.mm:34)
6  AsyncDisplayKit                0x100ac6a98 ASDeleteElementsInMultidimensionalArrayAtIndexPaths (ASMultidimensionalArrayUtils.mm:145)
7  AsyncDisplayKit                0x100a9907c -[ASDataController deleteNodesOfKind:atIndexPaths:completion:] (ASDataController.mm:302)
8  AsyncDisplayKit                0x100a99c44 -[ASDataController _deleteNodesAtIndexPaths:withAnimationOptions:] (ASDataController.mm:381)
9  Foundation                     0x18bbed804 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
10 Foundation                     0x18bb32760 -[NSBlockOperation main]
11 Foundation                     0x18bb22b18 -[__NSOperationInternal _start:]
12 Foundation                     0x18bbefba0 __NSOQSchedule_f
13 libdispatch.dylib              0x189fd69a0 _dispatch_client_callout
14 libdispatch.dylib              0x189fe4ad4 _dispatch_queue_serial_drain
15 libdispatch.dylib              0x189fda2cc _dispatch_queue_invoke
16 libdispatch.dylib              0x189fe6a50 _dispatch_root_queue_drain
17 libdispatch.dylib              0x189fe67d0 _dispatch_worker_thread3
18 libsystem_pthread.dylib        0x18a1df1d0 _pthread_wqthread
19 libsystem_pthread.dylib        0x18a1ded7c start_wqthread

**Comment by garrettmoon** [comment]
This is often caused by issues with the data controller, would you mind uploading a sample project where this reproduces reliably?

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#214
