### ISSUE TITLE
[Question] How to preserve the contentOffset of ASScrollNode?

### ISSUE THREAD

**Issue by xilin** [facebookarchive/AsyncDisplayKit#3252]
I'm using `ASScrollNode` inside a `ASCellNode`. It seems that when I push a new viewcontroller and pop back, the `tableView:nodeBlockForRowAtIndexPath:` is called and a new `ASCellNode` instance is created.

In the new creately cell node, `ASScrollNode`'s content offset is always `CGSizeZero`.

Is there any way to preserve the contentOffset?

**Comment by garrettmoon** [comment]
@xilin This is the perfect type of question for our slack channel: http://texturegroup.org/slack.html
