### ISSUE TITLE
IGListKit - Weird layout animation after view controller is visible

### ISSUE THREAD

**Issue by bevbomb** [facebookarchive/AsyncDisplayKit#3256]
I have a tab bar system and i'm using a ASViewController with a ASDisplayNode to wrap a ASCollectionNode. I'm using IGListKit to handle updates on the collection. 

The problem i'm having is when every i go to the tab which holds the view controller for the first time, all of the cells transition from the top left corner with a size of (0,0) to their proper sizes. I can see that the collection has been updated when the view controller loads but the cells content isn't being laid out until i actually access the view controller, I can see the white background for cells and the content transitions in.

My cells are using layout specs and automatically managing sub nodes. The node that i'm using to wrap the collection for the view controller. It doesn't matter which node i use, it still animates it like that.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#215
