### ISSUE TITLE
[RFC] Cell capability as an extension of ASDisplayNode

### ISSUE THREAD

**Issue by nguyenhuy** [facebookarchive/AsyncDisplayKit#3266]
Currently, `ASCellNode` is a subclass of `ASDisplayNode`. As a result, sometimes a display node must be wrapped inside a cell node to be used within a collection/table view. If we can find a way to implement cell node functionality as an extension of ASDisplayNode, we can turn ASDisplayNode into a magical class that can be used inside any container and can even be re-hosted from one to another!

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#218
