### ISSUE TITLE
How can I set up a 'pull-down' to  get the network data In ASCollectionNode? I need a custom? 

### ISSUE THREAD

**Issue by LeeJeanYi** [facebookarchive/AsyncDisplayKit#3274]
I would like to use  'pull-down' to load more data, but ASDK only provides pull to get data like 'willBeginBatchFetchWith' .

I need to do it by myself ?

Thx a lot  :)

**Comment by garrettmoon** [comment]
The best place to get help is in our slack channel: http://texturegroup.org/slack.html
