### ISSUE TITLE
Add target on ControlNode not working

### ISSUE THREAD

**Issue by Ghana93** [facebookarchive/AsyncDisplayKit#3276]
i added this code in LikeNode (in init method) of social app example,but its not working 
 
    [self addTarget:self action:@selector(likeTapped:) forControlEvents:ASControlNodeEventTouchUpInside];

    -(void)likeTapped:(id)sender {
     NSLog(@"Like Button Pressed");
    }
Please help
Thank you,
Gaurav

**Comment by garrettmoon** [comment]
@Ghana93 it looks like it's because the PostNode is changing it to be layer backed. In the latest master we've added an assert that prevents this. So now the example asserts on load when the PostNode tries to make it layer backed.

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#220
