### ISSUE TITLE
[ASVideoNode] Placeholder image not showing from HLS

### ISSUE THREAD

**Issue by fana605** [facebookarchive/AsyncDisplayKit#3279]
Hello,
Playing a live stream HLS works perfectly, but the placeholder image does not show. Is it suppose to show or is it even possible to get the first frame from a HLS stream?

Example of a HLS that plays well but does not show the placeholder image: https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

Thanks

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#222
