### ISSUE TITLE
Crash at screen rotating.

### ISSUE THREAD

**Issue by hstdt** [facebookarchive/AsyncDisplayKit#3282]
When I use Texture 2.3 instead of AsyncDisplayKit 2.2.1, a small project may crash when I rotate screen.(Xcode 8.3.2 macOS10.12.4)   
[the demo project here.zip](https://github.com/facebook/AsyncDisplayKit/files/955157/bugDemo.zip)

the difference:
![image](https://cloud.githubusercontent.com/assets/10215098/25387947/01d356ae-29ff-11e7-9e92-6856ad0348ab.png)

```
 *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 9 beyond bounds [0 .. 8]'
```
![image](https://cloud.githubusercontent.com/assets/10215098/25386772/1349d9b6-29fb-11e7-9ae6-cbaa955c55fa.png)

![image](https://cloud.githubusercontent.com/assets/10215098/25386610/840bf52c-29fa-11e7-9129-2c19accc1b90.png)

**Comment by ay8s** [comment]
Thanks for filing @hstdt. Can you file this over at https://github.com/texturegroup/texture/issues?

**Comment by garrettmoon** [comment]
Going to close this issue, please re-open on Texture if you're still seeing it!
