### ISSUE TITLE
ASTableNode can't support reloadData 

### ISSUE THREAD

**Issue by dennishappy** [facebookarchive/AsyncDisplayKit#3285]
// If you're looking for help, please consider joining our slack channel:
// http://asyncdisplaykit.org/slack

// The more information you include, the faster we can help you out! 
// Please include: a sample project or screenshots, code snippets
// AsyncDisplayKit version, and/or backtraces for any crashes (> bt all). 
// Please delete these lines before posting. Thanks!

**Comment by appleguy** [comment]
It looks like there is no content to your report...where's the description of the issue?

Please file an issue on the current project page, as ASDK moved to Texture: https://github.com/texturegroup/texture/issues

You need to include your current version of the framework and some additional information. If reloadData isn't available on the latest ASTableNode (check that you're on framework version 2.3.2), then you can always access the .view which does have reloadData.
