### ISSUE TITLE
[ASImageNode] Consider automatically applying .tintColor property without setting .imageModificationBlock

### ISSUE THREAD

**Issue by adremeaux** [facebookarchive/AsyncDisplayKit#426]
Here's the code:

```
    searchIcon = ASImageNode()
    searchIcon.image = UIImage(named: "IconSearch")?.imageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate)
    searchIcon.tintColor = UIColor.redColor()
```

No matter what color I put in tintColor, it's always tinted pure black. Am I using this improperly or is this attribute not supported?

**Comment by appleguy** [comment]
We did add support for tintColor, but it is possible that there is a bug.  Perhaps more likely, it may not be supported by ASImageNode to do the tinting automatically.  I'm pretty sure, however, that tint color notifications and property updates do propagate correctly.  The main intended usage of it is for custom classes that want to tap into tintColor.

**Comment by SilverEnderman** [comment]
In the meantime, are there any workarounds to allow us to use ASImageNode with a tinted template image?

**Comment by yxztj** [comment]
I'm facing the same issue, seems tintColor has no effect on ASImageNode.

**Comment by Jercik** [comment]
@SilverEnderman @yxztj just use ASImageNode's imageModificationBlock property. There is even ready to use ASImageNodeTintColorModificationBlock.

**Comment by SilverEnderman** [comment]
It works! awesome!

**Comment by markmark1** [comment]
Is there an example to use imageModificationBlock

**Comment by RuiAAPeres** [comment]
@Jercik I am seeing the same issue is affecting the `tintColor` on the `ASTextNode` is there a workaround for this? (it's in the context of this #571)

**Comment by appleguy** [comment]
@RuiAAPeres hey there — thanks for reporting the issue.  To be honest, I'm not very familiar with how tintColor behaves with some of these UIKit classes, as it does not appear to be very well documented.  E.g., is it supposed to change link colors?  But not any other color in the text?

I'd welcome any diffs changing the behavior, as it should be pretty easy to do by looking at the internals of ASTextNode.  Or, if you can describe the expected behavior or provide a test project comparing to UIKit, it will allow one of the many other developers on the project to implement it :).

**Comment by RuiAAPeres** [comment]
@appleguy hey there! The `tintColor` issue is described in #571.

**Comment by chrene** [comment]
@markmark1 something like this maybe: 
`imageNode.imageModificationBlock = ASImageNodeTintColorModificationBlock(.whiteColor())`

**Comment by ober01** [comment]
my solution  use `ASDisplayNode`  `init(viewBlock: ASDisplayNodeViewBlock)`

```
let node = ASDisplayNode(viewBlock: { () -> UIView in
                
                let imageView = UIImageView(image:   image?.imageWithRenderingMode(.AlwaysTemplate))
                imageView.alpha = alpha
                imageView.tintColor = color
                return imageView
            })
node.preferredFrameSize = image?.size ?? .zero
```

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#99

**Comment by varyP** [comment]
> @markmark1 something like this maybe:
> `imageNode.imageModificationBlock = ASImageNodeTintColorModificationBlock(.whiteColor())`

@RuiAAPeres @markmark1 
Possible to change it dynamically from say .white to .black later?
Setting it again makes no difference to the imagenode right now.

**Comment by ndemie** [comment]
> > @markmark1 something like this maybe:
> > `imageNode.imageModificationBlock = ASImageNodeTintColorModificationBlock(.whiteColor())`
> 
> @RuiAAPeres @markmark1
> Possible to change it dynamically from say .white to .black later?
> Setting it again makes no difference to the imagenode right now.

Ever figured this out?

**Comment by varyP** [comment]
> > > @markmark1 something like this maybe:
> > > `imageNode.imageModificationBlock = ASImageNodeTintColorModificationBlock(.whiteColor())`
> > 
> > 
> > @RuiAAPeres @markmark1
> > Possible to change it dynamically from say .white to .black later?
> > Setting it again makes no difference to the imagenode right now.
> 
> Ever figured this out?

Hey @RuiAAPeres @ndemie 

`
someImage.imageModificationBlock = ASImageNodeTintColorModificationBlock(someUIColor)        
someImage.setNeedsDisplay()
`

Remember to ask to re-render the image, only then will it show the new color.
Been working for fine for me after the setNeedsDisplay().
