### ISSUE TITLE
[ASViewController] Add a way to participate with ASLayoutSpec, analogous to -viewWillLayoutSubviews.

### ISSUE THREAD

**Issue by yury** [facebookarchive/AsyncDisplayKit#969]
Hi,

I am very impressed how easy I build layout with ASLayout. And I want use it not only in cells, but in ViewController.

I found ASViewController, but as I understand, I need to create ASDisplayNode separately and init ASViewController with it.

I wonder, if you have any plans to tune ASViewController API to be able to specify layout in it. For instance:

``` swift
class LoginViewController: ASViewController {
    private let _loginNode = ...
    private let _passwordNode = ...
    private let _loginButtonNode = ...

    override func viewDidLoad() {
        super.viewDidLoad()
        node.addSubnode(_loginNode)
        node.addSubdode(_passwordNode)
        node.addSubnode(_loginButtonNode)
    }

    // I think this method is missing...
    override func layoutSpecThatFits(constrainedSize: ASSizeRange) -> ASLayoutSpec! {
        return ...
    }
}
```

**Comment by fatuhoku** [comment]
@yury Where did you find the documentation for LayoutSpec? I don't understand it.

**Comment by yury** [comment]
@fatuhoku https://github.com/facebook/AsyncDisplayKit/files/15787/ASLayoutSpecs.10-12-15.pdf

**Comment by fatuhoku** [comment]
@yury Thanks, where did you find that link?!?!

**Comment by fatuhoku** [comment]
I'm also really confused about what constrained size actually is. I'm also really unclear about which of `layout`, `layoutSpecThatFits:` is or is not a part of the ASDK API.

@nguyenhuy

**Comment by levi** [comment]
I'd love to see something like this too, @yury. @appleguy, I know you've mentioned this in the past. Let's start the discussion on making this API a reality.

**Comment by appleguy** [comment]
@fatuhoku @yury This presentation of mine is not very good, but it does include essential information about the layout patterns.  @fatuhoku I think it would be particularly useful to you as it does compare those patterns (skip to 11 minutes).  This video is also linked at the very bottom (tiny font) on asyncdisplaykit.org:

https://www.youtube.com/watch?v=RY_X7l1g79Q

@yury there is not currently a layoutSpec method on ASViewController - this will be added soon, but in the meantime you must subclass the node that you provide to ASVC.  This is the same as how UIViewController started out, where for 4 or 5 years the iOS API did not provide -viewDidLayoutSubviews and it wasn't possible to implement layout in a view controller without doing it in an usual place like -viewWillAppear:.

**Comment by yury** [comment]
@appleguy thank you!

**Comment by hannahmbanana** [comment]
@yury @fatuhoku: check out the (work-in-progress) website documentation on ASLayout - http://asyncdisplaykit.org/docs/automatic-layout-basics.html

**Comment by appleguy** [comment]
@yury @fatuhoku - You can now do `self.node.layoutSpecBlock` which is handy for various use cases. We are actively working on designing an API that is more directly integrated with ASViewController so that it is discoverable and allows extended layout on top of existing `layoutSpecThatFits:` implementations that the node may also specify. 

For example, a node subclass may have a `layoutSpecThatFits:`, the node may have a layoutSpecBlock and the viewConteroller has a `layoutSpecThatFits:`, we have well defined ways to apply these layouts, but the work to be able to run multiple layout specs for a single is ongoing.

**Comment by yury** [comment]
@appleguy thanks

**Comment by appleguy** [comment]
We now have .layoutSpecBlock(), a block you can provide on any ASDisplayNode that can take the place of -layoutSpecThatFits.

This work perfectly for ASViewController if you want to do something like initWithNode:[[ASDisplayNode alloc] init].  You can add subnodes (or better yet, do self.node.usesImplicitHierarchyManagement = YES), then provide the layout spec block (typically best to define this in -init).

The only trick is that this cannot be used with any class that defines -layoutSpecThatFits as a method.  This does limit the usefulness quite a bit, so we have an important task on the team roadmap already to address this by allowing any two layout spec definitions to both apply themselves.

**Comment by hannahmbanana** [comment]
@maicki: if this isn't already in your layout API improvement to-do list, could you add it?

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#118
