### ISSUE TITLE
[ASCollectionView] Support willDisplaySupplementaryNode: delegate method.

### ISSUE THREAD

**Issue by stowy** [facebookarchive/AsyncDisplayKit#983]
ASCollectionView currently passes through this call:

``` objc
- collectionView:willDisplaySupplementaryView:forElementKind:atIndexPath
```

and likely this one:

``` objc
- collectionView:didEndDisplayingSupplementaryView:forElementOfKind:atIndexPath:
```

Can these be converted to their node equivalents and called at the correct time? Currently they are called on insert sections.

**Comment by appleguy** [comment]
https://github.com/facebook/AsyncDisplayKit/pull/1022 improves safety by ensuring this method isn't called.  It will take a bit more work to ensure it is called only at the right time - mainly editing transactions are the risk.  99% of the time it is called, we just need to forward it.

**Comment by appleguy** [comment]
@aaronschubert0 you could add this one!

**Comment by aaronschubert0** [comment]
@appleguy Will take a look :)

**Comment by garrettmoon** [comment]
This issue was moved to TextureGroup/Texture#119
